### ISSUE TITLE
Feedback / Suggestions

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#1]
Thanks for participating in this project. Please leave your comments, feedbacks and/or suggestions below. :+1:

**Comment by TrySound** [comment]
Why gaze in dependencies?

**Comment by ghost** [comment]
@TrySound Good catch. I was using `gaze` at first, but later switched to `chokidar`. 

`Fly.prototype.watch`, uses `util/watch` under the hood which is just a wrapper for `chokidar.watch`.

**Comment by TrySound** [comment]
@bucaran Right choice.)

**Comment by TrySound** [comment]
@bucaran It watches only `change`? I think better also `add` and `unlink`

**Comment by ghost** [comment]
@TrySound Thank you!. The watch API is still largely WIP, hence the negligence on my part.

**Comment by TrySound** [comment]
@bucaran [postcss](https://github.com/postcss/postcss) uses babel without dist compilation. Try it.

**Comment by ghost** [comment]
@TrySound Cool! Thanks.

**Comment by TrySound** [comment]
@bucaran Til, we have a few plugins. Maybe change plugin API to

```
module.exports.plugin = function () {
  // Plugin
};
```

It's more clean.

**Comment by TrySound** [comment]
@bucaran Or we can use both of this by detecting function and object

**Comment by TrySound** [comment]
@bucaran But the best solution for me is just

```
module.exports = function () {};
```

And name will be parsed from module name. `-`, `.` will be camelized.

**Comment by TrySound** [comment]
@bucaran This module works fine with it.
https://github.com/jonschlinkert/load-plugins

**Comment by ghost** [comment]
@TrySound Good suggestions. Let me see how this module works and what it would take to incorporate into Fly. I also need to improve the documentation and add more examples. Also plugins!

**Comment by TrySound** [comment]
@bucaran 

``` js
var arrayOfPlugins = require('load-plugins')('fly-*', {
  strip: 'fly',
  camelize: true
});
```

Later these options will defaults after my PRs.

**Comment by ghost** [comment]
@TrySound Seems clean from an interface POV, but do you think there is any chance we could roll our own or find a simpler in-between solution without deps?

**Comment by TrySound** [comment]
@bucaran I read whole code of this and more another. This module is great.

**Comment by TrySound** [comment]
@bucaran Do not afraid dependencies. You need to afraid only `imagemin` :)))

**Comment by ghost** [comment]
@TrySound LOL anyhow tl;dr, what do we get with this dep that is not already provided out of the box here?

**Comment by TrySound** [comment]
@bucaran Did you see gulp code? Modularity rules the world.

**Comment by ghost** [comment]
@TrySound Sorry, do you mean the code in your post, or [this](https://github.com/jonschlinkert/load-plugins#with-gulp)?

EDIT: Mmm, perhaps you would like to be able to load plugins with a watermark other than `fly-*`. Correct?

**Comment by TrySound** [comment]
I meant gulp source code. It's small js file with some dependencies. Every dep easier to contribute and fix.
I think ['fly-_', 'fly._'] is nice. Also it fixes some problems out of the box.

**Comment by ghost** [comment]
@TrySound OK, so to be clear, the idea is to support loading modules other than `fly-*` or are you fine with that?

**Comment by TrySound** [comment]
@bucaran We can you only fly-*, but it will make a little more helpful work.
Also if we want to use postcss for example, we can use load-plugins as dep, which already exists. This will work a little faster.

**Comment by TrySound** [comment]
@bucaran Sugget to open gitter room

**Comment by ghost** [comment]
@TrySound I forgot to post the link => https://gitter.im/flyjs/fly

**Comment by eranimo** [comment]
How does Fly compare to gulp in performance and speed?

**Comment by ghost** [comment]
@eranimo Definitely an issue that should be clearly explored. Unfortunately I haven't run any _meaningful_ tests yet. I doubt we will gain any significant performance in terms of _speed_, but I haven't noticed anything strange _so far_ anyway.

Plugins are truly anorexic wrappers around the utilities, so that would never be the bottleneck. Promises in general are known to be _slower_ than using vanilla callback control flow, **however** I don't know if this would actually be a performance hit after reading [this](http://thanpol.as/javascript/promises-a-performance-hits-you-should-be-aware-of/).

**Comment by dashed** [comment]
**Disclaimer:** I haven't actually used fly. But the following are my opinions after glancing at the source code and the API docs.

---
- `Fly.prototype.reset()` seems awkward and requires the user to intimately know the inner workings of fly. Be better to make this a private API, and have separate API to reset `this._src` and `this._filters` individually.
- I think all instances of `filter(s)` should be renamed to `transform(s)`. (it just makes more sense to me as a gulp user that uses [through2](https://github.com/rvagg/through2) a lot)
- Is there a way to load custom plugins **dynamically** (other than through the constructor)? something like this:

``` js
exports.scripts = function* () {
  yield this
    .source("src/**/*.coffee")
    .coffee({/* ... */})
    .uglify({/* ... */})
    .plugin(require('./fly-plugins/something')) // manually load local plugin
    .concat("all.min.js")
    .target("dist/js")
}
```

**Comment by ghost** [comment]
@Dashed Thanks for the feedback.

Yes, `reset` should be private.

I can rename filter to transform internally, but `filter` has the same number of characters as `source` and `target` which makes it looks great on display. If a lot of people feel transform is better though, I'll rename it.

There is no special magic going on inside that Flyfile, so sure, you could load any plugins not listed as deps in your `package.json` and under `node_modules/` yourself without problems.

We don't even need to call a `plugin` method. The Fly instance could be extended with a reference to `require` or a method that wraps require and can later be adapted to `System.import`, etc.

**Comment by dashed** [comment]
The following LOC reminds me of [transducers](https://github.com/jlongster/transducers.js) (from clojure): https://github.com/flyjs/fly/blob/5724af0fb3a2f1170138f8ecc793d6b54f5ecfce/src/fly.js#L120-L124

I think it'd be really cool to be able to use transducers with flyjs. A combination of transducers, promises, and generators would be very superior to node.js streams. 

flyjs could provide a nice-ish API that wrap 'transducer-like' API under the hood.

---

I think there are benefits to being able to access some sort of `metadata` object which may contain the file descriptor for filter/transform. Also, an actual `filter()` method may be beneficial, and being able to add more files:

``` js
exports.scripts = function* () {
  yield this
    .source(globs)
    .filter((data, metadata) => {
      metadata.fd; // access file descriptor
      // remove files in the pipe-like chain.
      // useful applications include removing files 
      return condition; 
    })
    .transform((data, metadata) => {
      // .transform is renamed from this.filter()
    })
    .source(moreGlobs) // be able to add more files
    .target(dest)
}
```

**Comment by ghost** [comment]
> Rename `filter` to `transform`.
> 
> TBH this was originally named `map`, but I felt some folks would not like that one either, so `filter` was the one I ended up choosing.

@Dashed Gotcha. Let me make a point of this while I am working on the other stuff. 

<hr>

I hope I am not making any false assumptions, but perhaps you are trying to replicate your gulp-like tasks here? Since you are inside a _co-wrapped_ generator function, you don't have to compose everything in a single sequence.

You can split up your tasks and sub tasks into promise/s returning functions and `yield` them inside the main task.

Anyhow, it would be really helpful if you could describe an actual use case, I am trying to go over your example, but I would like to see how this applies to a real world usage.

> The following LOC reminds me of transducers (from clojure): https://github.com/flyjs/fly/blob/5724af0fb3a2f1170138f8ecc793d6b54f5ecfce/src/fly.js#L120-L124

Thanks for drawing that comparison. I am not extremely proud of that snippet of code, but I do like it as the functional-ish solution it is. Basically each unwrapped data source is reduced (have all filters applied) in that recursive function. 

> flyjs could provide a nice-ish API that wrap 'transducer-like' API under the hood.

I totally dig this idea.

**Comment by nmabhinandan** [comment]
Just a thought.., Why not ES6 modules? Why not use `babel-core` to tranform flyfile on the fly?

**Comment by ghost** [comment]
Indeed, this is coming in `v0.0.5`, very soon (as in the next following hours.) 
Please see here => https://github.com/flyjs/fly/issues/12 :smile:

**Comment by iamstarkov** [comment]
I vote +1 for renaming `filter` to `transform`. because "filter" create wrong associations with filter methods for iterable objects.

**Comment by ghost** [comment]
Do notice there would be no name colliding though, it's just a semantic inconsistency.

I understand your point, and this was brought up before. The reasons I choose `filter` are:
- 6 letter word so it would nicely align with `source` and `target`.
- Although the function you pass into `Fly.prototype.filter` is indeed a _transform_ function, this is not a through stream. Calling `filter` just pushes the function into `this._filters` which are applied recursively to the unwrapped source when the promise resolves at some point.

I am slightly leaning towards `filter` because it's shorter than `transform` yet readable, but if we must change this, we should.

Here is another suggestion, "_`Fly.prototype.funnel`_", a bit obscure, but truer to what's actually happening behind the scenes.

**Comment by MadcapJake** [comment]
I don't mind that it's `filter`. The only difference between fly's `filter` and the conventional `filter` function is that conventionally, `filter` transforms based on a predicate.  Just think of fly's `filter`'s "predicate" as the extension accepted or the previous filter's function in the chain.  In some ways, I feel that the use of the word "filter" in this way feels more naturally filter-like than the more general return-if-predicate-true `filter`.  In fact, the general structure of chaining source to filters to target looks like layers of filters as in a water filtration system:

> ![305px-water_filtration_systems](https://cloud.githubusercontent.com/assets/3377525/8761871/05d29826-2d2d-11e5-8db3-8478c7141d4a.png)
> "<a href="https://commons.wikimedia.org/wiki/File:Water_Filtration_Systems.png#/media/File:Water_Filtration_Systems.png">Water Filtration Systems</a>" by <a href="//commons.wikimedia.org/wiki/User:Ivan_Akira" title="User:Ivan Akira">Ivan Akira</a> - <span class="int-own-work" lang="en">Own work</span>. Licensed under <a href="http://creativecommons.org/licenses/by-sa/3.0" title="Creative Commons Attribution-Share Alike 3.0">CC BY-SA 3.0</a> via <a href="https://commons.wikimedia.org/wiki/">Wikimedia Commons</a>.

However, if the consensus really is for changing it, here are some other potential (6-letter) words to consider: `mutate`, `change`, `evolve`, or `modify`.

**Comment by ghost** [comment]
@MadcapJake Awesome :+1: 

@iamstarkov Let's focus on more critical issues first and we can revisit this later.

→ #57

**Comment by ghost** [comment]
Thanks for your feedback during Fly's initial iteration.

##### If you have a feature request, suggestion or question, please [open a new issue](https://github.com/flyjs/fly/issues/).

:+1:
