### ISSUE TITLE
No export with require('Fly')

### ISSUE THREAD

**Issue by MadLittleMods** [lukeed/taskr#100]
The following snippet throws a `object is not a function`(iojs v2.3.3) or `Fly is not a function`(iojs v3.2.0) error.

``` js
let Fly = require('fly');
const fly = new Fly();
```

---

[_Discussion on Gitter_](https://gitter.im/flyjs/fly?at=55e655fee5564d685efaff5b)

**Comment by ghost** [comment]
The problem is Fly is not correctly exporting the Fly object. I will submit a fix with this in the next minor bump. Thanks @MadLittleMods :+1:
