### ISSUE TITLE
source maps not working with concat

### ISSUE THREAD

**Issue by sylvainpolletvillard** [lukeed/taskr#102]
This is my flyfile:

```
await this
        .source([
            "dist/tmp/libs.js",
            "dist/tmp/tags.js",
            "dist/tmp/scripts.js"
        ])
        .concat("game.js")
        .target("dist")
```

My final goal is to have multi level source maps, but at first I would like to have working source maps after concatenation.

Fly is generating a game.js.map, but the **path** of source files is not preserved :

```
"{\"version\":3,\"sources\":[\"libs.js\",\"tags.js\",\"scripts.js\"],\"names\":[],\"mappings\":\"AAAA;AACA;AACA;ACFA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;ACnBA;AACA;AACA;AACA;AACA;AACA;AACA\",\"file\":\"game.js\"}"
```

Also, there are no `//# sourceMappingURL=/dist/game.js.map` comment generated at the end of game.js file

Am I doing something wrong ?

**Comment by lukeed** [comment]
No, I don't think you were doing anything wrong. 

Sourcemapping was actually quite unreliable (and not originally meant to be a core feature), so it was removed in version 0.8.6. Besides, most tools and tool-plugins can handle their own sourcemaps; eg: Babel, Less, Sass, etc.
