### ISSUE TITLE
Tasks descriptions missing from output for cli.list

### ISSUE THREAD

**Issue by marionebl** [lukeed/taskr#109]
When adding @desc comments to tasks they are not printed in the output of `cli.list`, although this behavior is expected according to the [documentation](https://github.com/flyjs/fly/tree/cb53bf771cec252a58e48f280a6e573ad051ca34/docs#features).

``` js
export async function copy() {
    /** @desc copies all files from source to distribution */
    return await this.source(paths.source).target(paths.distribution);
}
```

```
fly --list
Available tasks

  "copy"
```

This appears to be a problem with:
- Missing [unit tests](https://github.com/flyjs/fly/blob/master/test/cli.js#L34)
- babel gobbling up the comments when transpiling
- different babel configs for building fly (hardcoded in package.json, flyfile), fly tests (babel-node, hardcoded in package.json) and comprehending fly-files and fly-plugins (require-hook, hardcoded in cli/spawn)

**Comment by lukeed** [comment]
This is indeed a bug. Babel is removing all tasks' comments.

If @bucaran still believes this is a nice feature for Fly, then we'll add the future tag as this certainly will be fixed/maintained in the coming versions. Fly will be moving to ES5, so no "gobbling" will occur :stuck_out_tongue_winking_eye: 

(PS: J, :+1: from me for adding this ti `fly-cli` only.)
