### ISSUE TITLE
Fly cut chain after `Fly.prototype.target`

### ISSUE THREAD

**Issue by petamoriken** [lukeed/taskr#110]
enable to connect pipe after `gulp.dest` in Gulp:

```
gulp.task("default", function() {
    gulp.src("test.js")
        ...
        .pipe(rename("build.js"))
        .pipe(gulp.dest("dest"))
        ...
        .pipe(uglify())
        .pipe(rename("build.min.js"))
        .pipe(gulp.dest("dest"));
});
```

So I want to write a code like above in Fly:

```
export default funciton* () {
    yield this.source("test.js")
        ...
        .rename("build.js")
        .target("dest")
        ...
        .uglify()
        .rename("build.min.js")
        target("dest");
}
```

But Fly cut chain after `Fly.prototype.target`. Please fix it.

**Comment by petamoriken** [comment]
Or a code below is better in Fly?

	export default funciton* () {
		yield this.start(["build", "minify"])
	}

	export funciton* build() {
		yield this.source("test.js")
			...
			.rename("build.js")
			.target("dest")
	}

	export funciton* minify() {
		yield this.source("dest/build.js")
			...
			.uglify()
			.rename("build.min.js")
			target("dest")
	}

**Comment by petamoriken** [comment]
Or should I write a code as below?

```
export default funciton* () {
    yield this.start(["build", "minify"])
}

export funciton* build() {
    yield this.source("test.js")
        ...
        .rename("build.js")
        .target("dest")
}

export funciton* minify() {
    yield this.source("dest/build.js")
        ...
        .uglify()
        .rename("build.min.js")
        target("dest")
}
```

**Comment by ghost** [comment]
@petamoriken Correct. `target` appears to "cut" the chain, because it resolves the promise sequence, which is the intended behavior.

Please use the second provided example. You may also declare all your transformations inside a single generator function.

**Comment by petamoriken** [comment]
@bucaran Thank you for your quick answer :+1:
 I understood why `target` "cut" the chain.

**Comment by ghost** [comment]
:smile: No prob.
