### ISSUE TITLE
How do I use fly with rollup and babel?

### ISSUE THREAD

**Issue by leon** [lukeed/taskr#113]
I would like to use fly, since it's easier to understand than gulp or grunt.
And babel is awesome

But now I want to package it for the web, I haven't tried rollup yet, but it looks like it could be a good fit for bundling all the transpiled modules into one bundle.

But since rollup takes a "entry point" I'm not sure how it fits with fly?

https://github.com/rollup/rollup-plugin-babel

**Comment by bucaran** [comment]
Hi Leon

I am not so familiar with using Rollup yet, so I can't tell you what's really needed. In the meantime while I figure this out, you are most welcome to jump in and come up with a workflow. Perhaps a plugin would be needed?

Best

**Comment by leon** [comment]
Rollup doesn't take raw data as an input, but a reference to a "main" file.

So `.source(...glob)` doesn't really fit.

gulp does this by having an option object on the `.src([...], { read: false })` which makes the globed file paths getting passed instead of the raw data.

there are a couple of scenarios where you would want to pass along the filenames instead, so maybe we should add a `.sourceFiles(...glob)`?

**Comment by ghost** [comment]
@leon `.source` takes files not data, is not that what we need here?

**Comment by leon** [comment]
rollup has this api

``` js
import { rollup } from 'rollup';
import babel from 'rollup-plugin-babel';

rollup({
  entry: 'main.js',
  plugins: [
    babel({
      exclude: 'node_modules/**',
      sourceMap: true
    })
  ]
}).then(...)
```

And If I where to write a `.filter` plugin, how would I pass the `main.js`?
I'm not sure how to call rollup correctly, it is promise based, but you haven't got an example on how to write a plugin which uses promises.

**Comment by ghost** [comment]
@leon Oh, I was sending you in the wrong direction. I think you should take a look at [fly-eslint](https://github.com/bucaran/fly-eslint/blob/master/index.js) and [fly-mocha](https://github.com/bucaran/fly-mocha/blob/master/index.js). Another one that can point you in the right direction would be [fly-browserify](https://github.com/MadcapJake/fly-browserify/blob/master/index.js).

**Comment by leon** [comment]
Thanks I'll have a look :)

**Comment by s3ththompson** [comment]
I messed around with this for a while and couldn't get anything working.

@bucaran @Rich-Harris I believe the problem here is that the Rollup API expects a filename entry point (e.g. `main.js`) while the Fly API only exposes _every_ globbed file with `Fly.prototype.unwrap`. `unwrap` works with Browserify, since Browserify has an `add` method to add an arbitrary number of files.

Any ideas for how to make Fly work with Rollup?  I'm happy to contribute once the direction is clear.

**Comment by Rich-Harris** [comment]
There's a plugin that lets you use multiple entry points, which may help: https://github.com/eventualbuddha/rollup-plugin-multi-entry

Also, plugins give you complete control over the loading process, so if necessary you can (for example) load modules from memory, or from a stream of some sort. Happy to try and help figure out the best workflow if you can point me in the right direction! Feel free to ask questions on the Rollup issue tracker or on [Gitter](https://gitter.im/rollup/rollup) if that's preferable

**Comment by girvo** [comment]
Hey all, I'm curious if someone would like me to take a crack at this? I think I've got the hang of fly's API now and I'm quite curious about Rollup!

**Comment by ghost** [comment]
Sure!  @lukeed Thoughts?

**Comment by lukeed** [comment]
I actually was making a fly-rollup plugin this weekend. I halted on it in favor of fly-browserify... but maybe I'll open it back up

**Comment by adrianthewriter** [comment]
I was able to get basic rollup support by using this filter in my flyfile:

``` javascript
    .filter((data) => {
      return this.unwrap((files) => {
        return rollup.rollup({
          entry: files[0].toString(),
          plugins:[]
        }).then(function(bundle) {
          var result = bundle.generate({
            sourceMap: 'true',
            format: 'es6'
          });
          return {
            code: result.code,
            map: result.map,
            ext: '.js'
          }
        })
      })
    })
```

You just have to import rollup at the top of the flyfile. I just wanted to share. Maybe someone can use this info to build a proper fly-rollup plugin at some point.

**Comment by frantic1048** [comment]
@ambrooks Your filter works well~

I'm using `fly-esnext` .

I found If I do `import rollup from 'rollup'` in flyfile, node says rollup is undefined.
With `const rollup = require('rollup')` , it works. 

Does anyone have an idea about this ?

**Comment by lukeed** [comment]
@frantic1048 Try:

``` js
import { rollup } from 'rollup';
```

**Comment by frantic1048** [comment]
I just builded a [fly-rollup](https://github.com/frantic1048/fly-rollup) plugin with help of @ambrooks 's filter, you can take a look at it. ヾ(ﾟ∀ﾟ○)ﾂ

**Comment by ghost** [comment]
Nice LICENSE.

**Comment by lukeed** [comment]
New license called "DAFUQ" for "do whatever dafuq you wanna do"
