### ISSUE TITLE
Upgrade to Babel 6

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#115]

**Comment by marvinroger** [comment]
Babel must be upgraded ASAP to 6 as [every single example using Babel](https://github.com/bucaran/fly/tree/master/examples/babel) fails with `TypeError: (0 , _typeof3.default) is not a function` (see https://phabricator.babeljs.io/T6644). The `fly-babel` package requires `*` version, so it requires Babel 6, and it seems there is a conflict between `babel-runtime` and `fly-babel` not being the same Babel version. Or maybe I don't get a thing?

**Comment by marvinroger** [comment]
Nevermind, fly itself from npm is broken because of Babel 6. Just clean install from npm, and try to run `fly -h`. It fails with:

```
node_modules/fly/node_modules/babel-runtime/helpers/typeof.js:14
  return obj && typeof _symbol2.default !== "undefined" && obj.constructor === _symbol2.default ? "symbol" : typeof obj === "undefined" ? "undefined" : (0, _typeof3.default)(obj);
                                                                                                                                                                             ^

TypeError: (0 , _typeof3.default) is not a function
```

Same as my comment above, the `package.json` of the latest npm version requires Babel 6. @bucaran, maybe it's time to push a newer version to the registry, as the `package.json` in this repo explicitely uses Babel 5, it would fix the issue.

**Comment by ghost** [comment]
I will try to do that to fix the build ASAP and concentrate on upgrading to Babel 6 later on then.

**Comment by marvinroger** [comment]
Yup, by the way, thanks for this great tool! Let me know if you want me to test anything.

**Comment by ghost** [comment]
fafd2a2fbd192fc1c82edf004da47399fab5d558

Still need to upgrade to Babel 6.

**Comment by marvinroger** [comment]
Great, it works now. I can upgrade to Babel 6, I just did on my side. Will submit a PR soon.

**Comment by ghost** [comment]
Thanks! Can't wait to merge that :smile:

**Comment by ghost** [comment]
I think we can close this.

@marvinroger @iamstarkov /cc

**Comment by marvinroger** [comment]
Everything is upgraded, so yes. :+1:
