### ISSUE TITLE
Can't get fly to run on Windows 10 x64, Node 5.0 (and 5.1)

### ISSUE THREAD

**Issue by TheVoidSeeker** [lukeed/taskr#116]
When I install fly with `npm install -g fly` it installs version **0.8.3** without problems.
Calling `fly` results in:

> [PATH_TO_NPM]\node_modules\fly\node_modules\babel-runtime\helpers\typeof.js:14
>   return obj && typeof _symbol2.default !== "undefined" && obj.constructor === _symbol2.default ? "symbol" : typeof obj === "undefined" ? "undefined" : (0, _typeof3.default)(obj);
>                                                                                                                                                                              ^
> 
> TypeError: (0 , _typeof3.default) is not a function
>     at exports.default ([PATH_TO_NPM]\node_modules\fly\node_modules\babel-runtime\helpers\typeof.js:14:174)
>     at Object.<anonymous> ([PATH_TO_NPM]\node_modules\fly\node_modules\babel-runtime\regenerator\runtime.js:652:69)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> ([PATH_TO_NPM]\node_modules\fly\node_modules\babel-runtime\regenerator\index.js:19:18)
>     at Module._compile (module.js:425:26)

Then I tried `npm update -g fly` which resulted in a fly version of **1.1.9**, which shouldn't exist as far as I know.

Calling `fly` now results in:

> The system cannot find the path specified.

**Comment by marvinroger** [comment]
The issue is known, see https://github.com/bucaran/fly/issues/115
It has to do with Babel 6 and the way Fly declares its dependencies.

**Comment by ghost** [comment]
I think fafd2a2fbd192fc1c82edf004da47399fab5d558 fixes this issue.

@TheVoidSeeker Would you mind checking again?

**Comment by TheVoidSeeker** [comment]
Now the following happens, when i call `fly`

> module.js:340
>     throw err;
>     ^
> 
> Error: Cannot find module '../dist'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:289:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> ([PATH_TO_NPM]\node_modules\fly\bin_index:2:1)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Function.Module.runMain (module.js:457:10)

**Comment by marvinroger** [comment]
Strange, it works fine on Linux and there is no platform-depemdant code.. I'll check.

**Comment by marvinroger** [comment]
It works fine for me on Windows 10 x64 with Node 5.1. Maybe the installation failed due to the previous not-working build?

Try in a folder without any flyfile:

```
npm -g unlink fly
npm cache clear
npm -g install fly
fly
```

**Comment by TheVoidSeeker** [comment]
Yes, that works. It is kinda weird, because I thought I tested in on a fresh node 5.1.0 install.
Now `fly -v` works and reports the correct version (0.8.4).

**Comment by marvinroger** [comment]
I suspect Babel to have done a mess. Feel free to close this issue if the problem is gone.

**Comment by ghost** [comment]
@TheVoidSeeker @marvinroger Thanks fellows!
