### ISSUE TITLE
Make Fly Logo 2 F parallel side by side as symbol for flyer

### ISSUE THREAD

**Issue by HansS** [lukeed/taskr#117]
See quick paint sample
![fly logo](https://cloud.githubusercontent.com/assets/43744/11426929/babfc26a-945f-11e5-9df4-863ae8b1046d.png)

**Comment by ghost** [comment]
I tried googling "symbol for flyer", but still could not understand what you meant. Sorry. Can you explain again?

If you want to give it a shot, I used Pixelmator:

[fly.txt](https://github.com/bucaran/fly/files/45107/fly.txt)

Download and change extension to `.pxm`.

**Comment by HansS** [comment]
The 2 F back to back should look like airplane with the wings as F!

Date: Thu, 26 Nov 2015 08:38:11 -0800

**Comment by lukeed** [comment]
I think @bucaran enjoys the current logo. :laughing: Keeping this open?

**Comment by ghost** [comment]
@HansS's idea is fine, I just really like the current logo. 

I posted the original one as a shot on Dribbble and earned just a few claps. Good enough for me :smile: 

https://dribbble.com/shots/2100194-Fly
