### ISSUE TITLE
Tests fail on Build

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#122]
Cloning fresh repo, on 'postinstall', `npm run build` is ran, which includes the test suite.

10+ tests error out.

Using the `package.json` I've included [here](https://github.com/lukeed/fly/blob/writefile/package.json) not only upgrades everything babel-related to version 6.3, but it brings the number of failed tests down to 2 (the last two).

Not yet a PR because I'm not familiar enough with CLI stuff to solve the final 2 tests.

So, please look at or let me know if I'm using the wrong command to build Fly.

Thanks ~

**Comment by lukeed** [comment]
@bucaran The last 2 PRs from @marvinroger (upgrade to Babel6) are incomplete, thus breaking Fly.

Luckily, you didn't patch the version, so `0.8.4` still ships a functional version.

Locally reverting to commit `fafd2a2`, which means reverting `fly-babel` to `v0.6.0`. Also need to change the `babel-core` dependency from `*` to `^5.8.29`.

... That gets me _mostly_ there. The `dist` files will/can be run by the `bin/index` cli; however, there are still failing tests with regards the the cli scripts.

Not sure what to do from there.

That said, I'm also working on properly upgrading Fly to Babel6. All the new babel-runtime & transformer plugin changes produce a disjointed output. :worried:

**Comment by marvinroger** [comment]
Wait, CI passed on my 2 PRs, just look on Travis. But I'll take a look. :)

**Comment by lukeed** [comment]
Yea, I saw. Not sure why -- I ran and reran the same commands Travis does, then checked out different commits & ran them again.

Everything fails as of now, but checking out to pre-Babel6 only has `fly.cli` tests failing, which is improvement.

Only thing I can think of is the dependency management across the various packages. For example, a lot of packages in `fly` and `fly-util` and `fly-babel` were defined as `*`, and then these packages were fixed/specified at different points & patched at even later points.
Makes it really hard to go back and reproduce a stable Fly release.

**Comment by marvinroger** [comment]
I don't think switching back to pre-Babel6 is a good idea, we need to attempt to fix the issue on Babel 6.
Your package.json does not upgrade anything, as ^6.0.0 targets every Babel 6.x.x version (this is not the same as  `~6.0.0` which targets 6.0.x).

On a fresh git clone - npm install, I have 10 failing tests. But if you build or test one more time, there are 2 failing tests. Which is strange! But it is not related to your `package.json`.

**Comment by marvinroger** [comment]
The 2 remaining issues are coming from a [clor update](https://github.com/bucaran/clor/commit/e3a51be643c7100049678ff9be8f47ad08dec35a) that changed the output. I fixed it.

**Comment by lukeed** [comment]
@marvinroger totally agreed, Babel6 is definitely a must have. I was only reverting to find the point at which tests began to fail.

Also, the package.json in my fork isn't a fix. Whole bunch of local commits that I haven't squashed & pushed yet :wink: 

Intrigued by the Clor changes. Will take a look!

**Comment by marvinroger** [comment]
The failing output from the first install is:

```
  ✈  fly.*exec

    ✔ notify start event to observers

    ✖ plan != count
    ----------------
      operator: fail
      expected: 4
      actual:   1


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail


    ✖ test exited without ending
    -----------------------------
      operator: fail

```

I cannot reproduce it anymore, even after a clean reinstall.. Maybe it was related to some Babel cache, but let's say we were both unlucky. We will see what the CI will say once my coming PR is merged. ;)

For you record, clor's purpose is to output some color codes to some text. But before the commit I mentionned above, it was adding redundant color codes. The checks in the fly tests hard-code these color codes. So there was an issue!

@bucaran This could potentially be a breaking change (well, in the case of fly it is). You might consider bumping clor to 3.0.0? Remember semver is BREAKING.FEATURE.FIX :)

**Comment by lukeed** [comment]
Ah, did not see the hardcoded checks. Nice!

**Comment by marvinroger** [comment]
[And... it's green!](https://travis-ci.org/bucaran/fly/builds/99275969) :ok_hand:

**Comment by lukeed** [comment]
:raised_hands:

**Comment by ghost** [comment]
@marvinroger 

> his could potentially be a breaking change (well, in the case of fly it is). You might consider bumping clor to 3.0.0? Remember semver is BREAKING.FEATURE.FIX :)

Yes, you are absolutely correct and I completely forgot about that after merging a patch. Software is so fragile is scary.

Thank you @marvinroger and @lukeed. 

@lukeed Are you working on a different PR or can I merge @marvinroger clor fixes?

**Comment by lukeed** [comment]
@bucaran different PR that requires this one to be merged first :+1:

**Comment by ghost** [comment]
:+1:
