### ISSUE TITLE
Abort sequential chain on `task_error`

### ISSUE THREAD

**Issue by throskam** [lukeed/taskr#123]
For instance:

``` javascript

export async function foo () {
    console.log('Perform foo');
}

export async function bar () {
    console.log('Perform bar');
}

export async function error () {
    throw 'Something went wrong!';
}

export default async function () {
    await this.start(['foo', 'error', 'bar']);
}
```

The tasks `bar` is performed even if the previous task has failed.

The expected result can be achieved with the following:

``` javascript
export default async function () {
    this.on('task_error', function () { process.exit(1); });
    await this.start(['foo', 'error', 'bar']);
}
```

but I feel it should be the default behavior especially for tasks like linting or testing which should abort subsequent compilation or packaging tasks.

The error is _dismissed_ in the fly `exec` function:

``` javascript
*exec (task, value, inject = this) {
    _("run %o", task)
    try {
        const start = new Date()
        this.emit("task_start", { task })
        value = (yield this.host[task].call(inject, value)) || value
        this.emit("task_complete", {
            task, duration: (new Date()).getTime() - start
        })
    } catch (error) { this.emit("task_error", { task, error }) }
    return value
}
```

Either the error should be thrown or the fly `start` function should handle the `task_error` event.

I'm trying out fly and I didn't see any error handling example or convention on the matter so maybe I'm missing something ? How should I properly abort a tasks chain ?

**Comment by ghost** [comment]
This is a valid concern. There is currently no mechanism to abort a task depending on the result of another task, but this should not be too difficult to support.

There is a way to communicate an object between tasks using the _cascading tasks_ feature. Have a look [here](https://github.com/bucaran/fly/blob/master/examples/cascading/flyfile.js) and let me know if you could use this in your situation.

**Comment by throskam** [comment]
Hum, I thought about that but what about plugins then ? Should they all implement that logic ?
Seems cumbersome, I rather use the generators feature which allows exception to `bubble` to the top of the stack and then either fly catches them and gives an API to plug some error handling callbacks or simply throws them back to the tasks themselves where they can be catch if need be. 

Grunt and Gulp lack severely of a good error handling solution and I feel like fly could potentially offer an easy and elegant way of doing it using generator and async functions. (per task error handling :heart_eyes:)

Anyway, thanks for your quick response, for right now I'll use my hack which works fine for my use case :smile:

**Comment by lukeed** [comment]
@throskam The way it is now (as of recently), `plugin_errors` and `task_errors` will set the `exitCode` to `1`. This means that the terminal will still report a failed build sequence, but without killing the rest of the chain. 

Logically, it _does_ make sense to auto-kill the sequence on any task's error; however, this would also kill a `watch` runner, which defeats the purpose of a watcher.

**Comment by throskam** [comment]
You are totally right, the `process.exit(1)` was a quick hack for my use case but indeed it doesn't make much sense for watchers and the like. The tasks chain should be abort without killing the main process. 

But I still strongly feel like whenever an error occurs in a task, subsequent tasks should not be executed.

**Comment by lukeed** [comment]
I'd only agree as far as sequential tasks (`parallel: false`) are concerned, but even then, no process should be exited.

Parallel tasks are independent of one another -- that is the point, after all.

**Comment by throskam** [comment]
I agree, parallel tasks are creating new tasks chains that shouldn't be impacted by any errors in other chains.

Typically it would be for use cases such as `linting`, `compiling`, `packaging`.
It makes no sense to package if the compilation or linting process has failed.
