### ISSUE TITLE
remove sourcemaps from core

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#129]
Assign to a plugin, install if desired.

Many plugins/tools already handle their own mappings. For example, [fly-babel](https://github.com/bucaran/fly-babel) supports it inherently.

**Comment by ghost** [comment]
What about removing this feature completly? Maybe we could add source map support via a plugin instead.

**Comment by lukeed** [comment]
I'd be fine with that :+1: 
Would make it much simpler, especially considering that I encountered a couple other quirks with it

**Comment by ghost** [comment]
Let's get rid of them. Providing just core infrastructure is so much harder than I originally thought. Now, I would rather have a simple, but working piece of software, than the current sloppy SourceMap support.

**Comment by lukeed** [comment]
Let's do it then.

**Comment by ghost** [comment]
Is this high priority?

**Comment by lukeed** [comment]
I don't think it technically qualifies as "broken" -- mostly just annoying.

**Comment by ghost** [comment]
:+1: 

![](http://orig01.deviantart.net/fbc0/f/2012/129/d/b/scorpion_strangulation_fatality_mk_by_aeruhl-d4z67tk.gif)
