### ISSUE TITLE
Why was Babel downgraded to v5?

### ISSUE THREAD

**Issue by marvinroger** [lukeed/taskr#130]
@lukeed ?

**Comment by lukeed** [comment]
It was broken.

And we can't successfully upgrade to Babel6 runtime because it has 2 core bugs that affect Fly. Babel team has been made aware of these issues and are resolving them shortly.

**Comment by marvinroger** [comment]
Alright! Thanks for the info.

**Comment by lukeed** [comment]
No problem :) I'll ping you when it's been solved
