### ISSUE TITLE
Live Reloading

### ISSUE THREAD

**Issue by Immortalin** [lukeed/taskr#132]
Is there a way to live reload assets on change? Brunch can do this out of the box, I think this is a rather important feature. :D

**Comment by ghost** [comment]
I know there was someone who posted a simple snippet using `tiny-lr` to accomplish this.

Basically the mentality was, if it can be done outside of Fly, let's not add it into core and so we never did.

What do you think?

**Comment by Immortalin** [comment]
Hmm, do you think you can create a plugin for this? Brunch uses a plugin too. 
https://github.com/brunch/auto-reload-brunch

**Comment by ghost** [comment]
A plugin is fine! So, do you want _me_ to create the plugin or you would like to take a shot at it?

**Comment by Immortalin** [comment]
Uh, it would be great if you can do it, let just say my JavaScript code tend to leave a lot to be desired...

**Comment by lukeed** [comment]
You can just use regular ol' BrowserSync.

Perhaps you'd like to start with a starter kit, or at the very least, you can see how to incorporate live-reloading into any task. https://github.com/lukeed/fly-starter

As bucaran said, it's not something we plan to directly embed within the core of Fly.

Please let us know if you have any further issues. :)

**Comment by lukeed** [comment]
@Immortalin did everything work out for you?
