### ISSUE TITLE
Better error formatting (plugins)

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#14]
The current strategy for error formatting inside plugins is that plugins _are_ responsible for their special formatting needs.

The following is fine, since Fly will catch that plugin's _task_'s error and show some output, but in the future plugins should trace errors more gracefully.

``` js
module.exports = function () {
  return this.filter("pluginName", (src, opts) => {
    try {
      return ....
    } catch (e) {
      this.notify("plugin_error", { plugin: "pluginName", { ... } })
      throw e
    }
  })
}
```

Specially stack traces we can use `prettyjson` for the output.

I am thinking something along the lines of

``` js
function trace (e) {
  error(pretty.render(e)
    .replace(/(\sFunction|\sObject)\./g, `${fmt.blue("$1")}.`)
    .replace(/\((~?\/.*)\)/g, `(${fmt.gray("$1")})`)
    .replace(/:([0-9]*):([0-9]*)/g, ` ${fmt.yellow("$1")}:${fmt.yellow("$2")}`)
    .replace(new RegExp(process.env.HOME, "g"), "~")
  )
  return process
}
```

**Comment by stryju** [comment]
what about https://github.com/RReverser/better-log ?

**Comment by ghost** [comment]
@stryju Let's keep that one in the roadmap. As of [0.1.1](https://github.com/flyjs/fly/releases/tag/0.1.1) we have better stack tracing for fatal errors. Stills needs improvement though.

**Comment by ghost** [comment]
@stryju Closing this. I will look into `better-log` when we are ready to improve the stack tracing again.
