### ISSUE TITLE
Confusing error messages on invalid flyfiles

### ISSUE THREAD

**Issue by IvanSanchez** [lukeed/taskr#144]
I'm trying fly 1.0.0-beta4 on nodejs 4.4.0. When I copy-pasted this flyfile from the examples...

``` js
export default function* () {
    yield this.source("src/foo.js").uglify().target("dist")
}
```

... I got the following cryptic error message:

``` bash
/tmp/fly-test$ node_modules/.bin/fly default
stack: 
  - SyntaxError: Unexpected identifier
  -     at exports.runInThisContext (vm.js 53:16)
  -     at Module._compile (module.js 373:25)
  -     at Object.Module._extensions..js (module.js 416:10)
  -     at Module.load (module.js 343:32)
  -     at Function.Module._load (module.js 300:12)
  -     at Module.require (module.js 353:17)
  -     at require (internal/module.js 12:17)
  -     at Object.module.exports [as spawn] (/tmp/fly-test/node_modules/fly/lib/cli/spawn.js 20:9)
  -     at next (native)
  -     at onFulfilled (/tmp/fly-test/node_modules/fly/node_modules/co/index.js 65:19)
message: Unexpected identifier
```

An `Unexpected identifier` in `vm.js`? WTF?

When I edited the flyfile to conform with ES6, the problem went away:

``` js
exports.default = function* () {
    yield this.source("src/foo.js").uglify().target("dist")
}
```

```
/tmp/fly-test$ node_modules/.bin/fly default
[10:34:38] Flying with /tmp/fly-test/flyfile.js...
[10:34:38] Starting default
[10:34:38] Finished default in 22 ms
```

However, **any** syntax error in the `flyfile` will throw the same cryptic error message.

Therefore, I must ask for the following feature: **If the flyfile has syntax errors, have the error message print "Flyfile has a syntax error at line whatever, column whatever"**.

**Comment by lukeed** [comment]
Documentation hasn't been updated for the betas.

Babel has been dropped entirely, which means that native ES6 and 7 support has been dropped...which means Flyfiles can't be written in ES6 or 7.

There will be a fly extension that, once downloaded, will allow "native" support for Flyfiles and plugins in ES6/7.

This is what I've been doing for Flyfiles :::

``` js
// ...
var x = module.exports;

x.default = function * () {
  // yield this.....
}

x.lint = function * () {
  // ...
}

x.scripts = function * () {
  //
}
```

As per your suggestion for error-catching: I plan to catch the "invalid token" error, and direct people to the "fly-esnext" extension, once available.

**Comment by lukeed** [comment]
Closing. There is no documentation for `beta` since it's not released yet, but previous comment should suffice for now.

Please feel free to reply if you still have questions.
