### ISSUE TITLE
CLI: Passing Fly Tasks

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#149]
One cannot pass more than 1 task name to Fly successfully.

``` bash
# works, 'lint' task is run
fly lint

# fails, only 'scripts' task is run
fly lint scripts
```

Issue opened with Parsec [here](https://github.com/bucaran/parsec/issues/9)

**Comment by ghost** [comment]
82ae6a0d1d2f53d773f4d27f1b9eb5f5fb4a1e23
