### ISSUE TITLE
Please also support iojs

### ISSUE THREAD

**Issue by rwu823** [lukeed/taskr#15]
The same code pass on `node` but error in iojs:

> [SyntaxError:node_modules/fly-babel/index.js:2
>  return this.filter("babel", (src, opts) => {
>                                                         ^^
> Unexpected token =>]

**Comment by ghost** [comment]
@rwu823 :+1: 

It's coming in `0.1.1` with a more consistent support for other binaries as well :)

**Comment by ghost** [comment]
[`0.1.1` is out](https://github.com/flyjs/fly/releases/tag/0.1.1).

@rwu823 Let me know if you are still getting the same problem.

**Comment by rwu823** [comment]
Hi @bucaran 

I got some npm install  problems for `0.1.1`, but `0.1.0` is fine. any ideas?

```
$ npm install -g fly
```

``` shell
> fsevents@0.3.6 install /usr/local/lib/node_modules/fly/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "fly"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path /usr/local/lib/node_modules/fly/bin/index
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/fly/bin/index'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by ghost** [comment]
This could be a problem with your `python` version. What is your python's version?

[`chokidar`](https://github.com/paulmillr/chokidar), uses [`fsevents`](https://github.com/strongloop/fsevents), a native extension, hence `node-gyp` (node's favorite native extension build tool written in python) trying to compile that, though looking I am not completely sure.

I will isolate this issue and try myself. Hold on.

**Comment by ghost** [comment]
@rwu823 Got it. Fixes soon in `0.1.2`.

**Comment by rwu823** [comment]
:+1: Nice, waiting for release

**Comment by ghost** [comment]
One problem was in `package.json`, it is now `bin/index.js` not `bin/index`.

But there is another problem with the plugins in the `examples/` directory.

**Comment by ghost** [comment]
This should be fixed and working OK now. Please let me know if you have any other issues.

@rwu823
