### ISSUE TITLE
flyfile.js or Flyfile.js?

### ISSUE THREAD

**Issue by tomByrer** [lukeed/taskr#156]
https://github.com/bucaran/fly/tree/master/examples
Several folders, mostly near the bottom.
I'd prefer a standardized lowercase.

**Comment by lukeed** [comment]
As of 1.0, **only** lowercase is accepted.

Thanks for pointing out the examples. Git didn't register the de-capitalization as a rename event. :+1:

**Comment by ghost** [comment]
We used to support both formats, but decided to go with `flyfile.js` only when 1.0 landed.

See https://github.com/bucaran/fly/pull/147

**Comment by tomByrer** [comment]
Thanks guys!
