### ISSUE TITLE
AssertionError missing path on start

### ISSUE THREAD

**Issue by gaokun** [lukeed/taskr#160]
I just run `fly` after `npm install -g fly`, then got error blow.
- OS: CentOS 7
- fly: v1.2.0
- node:  v4.2.1
- npm: v2.14.7

![image](https://cloud.githubusercontent.com/assets/7044628/14404522/247616fe-feab-11e5-948c-40a5a150e7e7.png)

**Comment by lukeed** [comment]
Hi there,

Can you try specifying a direct path to your Flyfile? I think what's happening is that Fly is looking for a Flyfile in its current (installed) directory and not finding one. 

@bucaran did you have to specify a fly path when used globally before?

**Comment by ghost** [comment]
@lukeed Good question. I don't remember, but the logical behavior here is to look for a flyfile in cwd if none is given via `-f`, otherwise fail.

**Comment by lukeed** [comment]
Ya, agreed. Sounds like Fly is using its current directory as the cwd 
I'll take a look at it

**Comment by gaokun** [comment]
Hi Luke,

Oh man, this is kind of embarrassing. I was trying to use `flightplan` to auto-deploy nodejs app.
And `flightplan` uses 'fly' as command too(use a 'fly.js' in `flightplan` package itself as a short name).

But I am happy to help to figure this out. I am going to find a tool like gulp & grunt too.

I created `Flyfile` as Usage, don't know should I can add .js or not, and the lowercase thing, so I created all of them (with same content).
But I have to install fly with -g as global, coz have to run it in command line.

And got this:
![image](https://cloud.githubusercontent.com/assets/7044628/14405100/6bf99e2a-feb9-11e5-8ea2-ac67ea47ff0b.png)

Thanks
Ken

**Comment by ghost** [comment]
I think this does not make sense:

https://github.com/bucaran/fly/blob/master/lib/fly.js#L30

**Comment by ghost** [comment]
@gaokun WRT to flightplan, this is a known issue https://github.com/bucaran/fly/issues/49. 

We thought we could solve it, but never really paid much attention to it since we figured what were the odds? Go figure.

**Comment by gaokun** [comment]
Yeah, sure, anyway, honor to help. :)

**Comment by lukeed** [comment]
>  I am going to find a tool like gulp & grunt too.

Fly can do 95% of what Gulp and Grunt do :) We just don't have quite as many plugins yet...

> I created Flyfile [..] no `.js`

As of 1.0 release, it has to be `flyfile.js`. Where did you see Flyfile? It should be updated.

**Comment by lukeed** [comment]
@gaokun  The use of "Flyfile" is what's throwing your error.

@bucaran That's what it [used to be](https://github.com/bucaran/fly/blob/v0.9.0/src/fly.js#L21). Makes sense to me... if user uses Fly locally, in which case the `flyfile.js` will be spawning from the project's root anyway. I guess it should be `process.cwd()`

**Comment by ghost** [comment]
It should be process.cwd(), yep.

**Comment by lukeed** [comment]
Not that simple as it breaks half of tests :disappointed:

**Comment by ghost** [comment]
Then nevermind haha.

**Comment by gaokun** [comment]
@lukeed Great, I would like to use fly in next project.
I just found things about Flyfile here: https://github.com/bucaran/fly
![image](https://cloud.githubusercontent.com/assets/7044628/14405203/fadff9ac-febb-11e5-85d3-69d583ef6fc3.png)

OK, I know it should be "Flyfile" now, I saw it is JS grammar, so I didn't know should I add .js or not.
Maybe we should make it clear.

And in Usage, I just saw 'npm install fly', without '-g' ?
Then how to run it?

**Comment by ghost** [comment]
@gaokun So, what I used to do is to have ./node_modules on my PATH, allowing me to run fly (as well as any npm module) without installing it globally directly from the directory where I ran `npm i fly`. Does that make sense to you?

**Comment by lukeed** [comment]
Ah, I see where you got confused :)

"Flyfile" is just what we call it, but the actual file name is "flyfile.js". We have a whole set of [documentation](https://github.com/bucaran/fly/blob/master/docs/README.md) you might like.

As for local usage, you use it like any other npm binary. You can either access the bin directly:

``` bash
$ ./node_modules/.bin/fly
```

... but that sucks. So instead, what people usually do is declare a `script` command inside their `package.json` file.

``` js
{
  // ...
  "scripts": {
    "fly": "fly"
  },
  "dependencies": {
    // ...
    "fly": "^1.2.0"
  }
}
```

``` bash
$ npm run fly
```

You can check out an entire Fly setup [here](https://github.com/lukeed/fly-kit-web)

**Comment by ghost** [comment]
@lukeed Calling it flyfile.js everywhere seems overkill, but at least let's make a point to avoid saying Flyfile, and always refer to it in lowercase.

**Comment by lukeed** [comment]
@bucaran sounds good. check latest readme

**Comment by gaokun** [comment]
@lukeed @bucaran 
Thanks guys, I understand now, and it works fine already.
Sorry for I didn't check doc carefully.It is almost 2:00 AM here, going to bed.

Have a good day.
Ken

**Comment by lukeed** [comment]
@gaokun no worries man, thanks for checking us out! You pointed out an actual bug too, so thank you.

Take care :zzz:

**Comment by lukeed** [comment]
@bucaran  the `process.cwd()` worked after all. Tested it locally, was fine. Tests were failing because they were `chdir` mid-test. Refactored and theyre ok now
