### ISSUE TITLE
Add ability to pass arguments to tasks

### ISSUE THREAD

**Issue by danny-andrews** [lukeed/taskr#164]
The documentation doesn't mention any way to pass arguments to tasks, is there a way to do that?

**Comment by lukeed** [comment]
Yes! I don't think it's in the docs, but it's surely in the [tests](https://github.com/bucaran/fly/blob/master/test/fly.js#L79) and the [examples](https://github.com/bucaran/fly/blob/master/examples/cascading/flyfile.js).

**Comment by danny-andrews** [comment]
Oh, I meant is there a way to pass arguments via command line, e.g.  `fly mytask[cool,man]`? I guess I could just use `process.argv` and/or use an option parser like [minimist](https://github.com/substack/minimist).

**Comment by lukeed** [comment]
Oh, then this is more @bucaran's area 😜 We are using minimist, though. The catch-all is for tasks, so something can probably be done within that, but I'm not positive -- not too familiar with minimist.

**Comment by ghost** [comment]
We could expose minimist so that @danny-andrews can tap into it though.

@danny-andrews Could you briefly describe your use case, ie, what are you trying to do or rather why :)

**Comment by danny-andrews** [comment]
Sure! I just want a way to be able to pass arguments to the task when running them via the command-line, similar to how you can in Grunt and Rake.
Rake Example:

``` ruby
task :my_task, [:arg1, :arg2] do |t, args|
  puts "Args were: #{args}"
end
```

``` bash
$ rake my_task[1,2]
Args were: {:arg1=>"1", :arg2=>"2"}
```

This is very helpful if you want a variation of a particular task.

**Comment by lukeed** [comment]
The only immediate use case that I see merit to is passing in local-global (lol) variables. Something like:

``` bash
fly build:production
```

``` js
exports.build = function * (env) {
  var isProd = (env === 'production') || false;

  yield this.start([ ...normal tasks... ]);

  if (isProd) {
    yield this.start([ ...prod-only tasks... ]);
  }
}
```

Of course, one can also pass in new sources (and default to others), but I'm not sure how much that'd actually get used.

**Comment by danny-andrews** [comment]
Yeah, that's the type of use-case I was thinking of.

**Comment by lukeed** [comment]
Ok. If you want, you can [take a look](https://github.com/lukeed/fly-kit-web/blob/master/flyfile.js#L55) how I'm accomplishing the same thing right now, but without the CLI flag ofc.

Here, the use of the `build` task manually sets the `isProd` flag to true, and all other tasks will look for/behave based on that value.

**Comment by danny-andrews** [comment]
A more immediate use-case would be a `publish` task, where you want to pass in a version via the command line.

**Comment by danny-andrews** [comment]
I tried using minimist to parse command line args, but fly complains whenever I try to pass arguments.
flyfile.js:

``` javascript
const args = require('minimist')(process.argv.slice(2));
x['npm-version'] = function() {
  return this.shell('npm --no-git-tag-version version ' + args._[1]);
};
```

Command:
`fly npm-version -- 1.2.2`
Output:
`1.2.2 not found in Flyfile.`
Note, this actually does work, but it's annoying that it prints out an error because it's looking for a command named "1.2.2."
