### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by okunokentaro** [lukeed/taskr#17]
[Scroll to bottom for screencast.](https://github.com/flyjs/fly/issues/17#issuecomment-120636342)

<hr>

```
mkdir fly-sandbox && cd $_
npm i fly fly-eslint
touch Flyfile.js source.js
```

**Flyfile.js**

```
console.log('Flyfile.js 1');

exports.main = function* () {
  yield this
    .source('./source.js')
    .eslint();
}
```

**source.js**

```
console.log('source.js')
```

---

```
$(npm bin)/fly main
```

```
Flyfile.js 1
stack:
  - TypeError: Cannot read property 'filter' of undefined
  -     at plugins (~/Desktop/fly-sandbox/node_modules/fly/dist/util.js 247:14)
  -     at Object.callee$0$0$ (~/Desktop/fly-sandbox/node_modules/fly/dist/cli/spawn.js 49:38)
  -     at tryCatch (~/Desktop/fly-sandbox/node_modules/fly/node_modules/babel-runtime/regenerator/runtime.js 67:40)
  -     at GeneratorFunctionPrototype.invoke [as _invoke] (~/Desktop/fly-sandbox/node_modules/fly/node_modules/babel-runtime/regenerator/runtime.js 297:22)
  -     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/Desktop/fly-sandbox/node_modules/fly/node_modules/babel-runtime/regenerator/runtime.js 100:21)
  -     at onFulfilled (~/Desktop/fly-sandbox/node_modules/fly/node_modules/co/index.js 64:19)
  -     at ~/Desktop/fly-sandbox/node_modules/fly/node_modules/co/index.js 53:5
  -     at co (~/Desktop/fly-sandbox/node_modules/fly/node_modules/co/index.js 49:10)
  -     at toPromise (~/Desktop/fly-sandbox/node_modules/fly/node_modules/co/index.js 117:63)
  -     at next (~/Desktop/fly-sandbox/node_modules/fly/node_modules/co/index.js 98:29)
message: Cannot read property 'filter' of undefined
```

---
- Yosemite 10.10.3 (14D2134)
- io v2.3.3
- npm 2.11.3

Thanks.

**Comment by ghost** [comment]
This is a bug in the current release, I am landing a bugifx in 0.1.3 for this. The bug is in the plugins function in util.js

**Comment by okunokentaro** [comment]
Sounds good!

**Comment by ghost** [comment]
Do you mind trying again to see if [`0.1.3`](https://github.com/flyjs/fly/releases/tag/0.1.3) fixed it?

Thanks.

**Comment by ghost** [comment]
@armorik83 Ping.

**Comment by okunokentaro** [comment]
@bucaran Pong.
I tried again in the above code with fly.js 0.1.11 + fly-eslint 0.1.0.
Then now, the following error came out.

```
Flyfile.js 1
[10:30:23] Flying with /Users/armorik83/Desktop/sandbox/Flyfile.js...
[10:30:23] Starting "main"
[10:30:23] main failed due to TypeError: this.source(...).eslint is not a function
```

Do we require first to `fly-eslint` solving?

**Comment by ghost** [comment]
@armorik83 That's some progress. Whatever plugins you use, you need to install them via npm before running fly on the CLI. Fly will load all the plugins declared in your package.json and inside your node_modules directory.

Thanks

**Comment by okunokentaro** [comment]
uh-huh. I'll try it. :v:

**Comment by ghost** [comment]
I will write a Fly tutorial in the next hours. Thay should cover most cases like this. Maybe :)

**Comment by okunokentaro** [comment]
Cool! I become interested.

**Comment by ghost** [comment]
Fly@0.2.2 has been up for a while now. Please try again against the latest distribution, you should have no problems running this task or using [`fly-eslint`](https://github.com/bucaran/fly-eslint).

As promised I wrote a simple [tutorial](https://github.com/flyjs/fly/wiki/Quickstart) and terminal screencast as well.

**Comment by ghost** [comment]
# Screencast

[![asciicast](https://asciinema.org/a/23283.png)](https://asciinema.org/a/23283)

**Comment by okunokentaro** [comment]
Awesome! It was solved my lack.
I had a lazy such as I had not run `npm init`:joy_cat:
That's perfect.

**Comment by ghost** [comment]
:+1:
