### ISSUE TITLE
Replace Co with Bluebird/Creed

### ISSUE THREAD

**Issue by Akkuma** [lukeed/taskr#170]
Co is one of the slower, if not slowest, libraries for generators. https://github.com/briancavalier/creed/tree/master/perf

It would probably be beneficial to opt for a faster library.

**Comment by ghost** [comment]
I didn't know other than co when I wrote the first fly. It seems creed is a hell lot faster than co.

**Comment by Akkuma** [comment]
An alternative benchmark, which creed's is based on, https://github.com/petkaantonov/bluebird/tree/master/benchmark shows that you pretty much can't go wrong with creed or bluebird.

**Comment by lukeed** [comment]
I just looked into it for the first time too -- Pretty cool!

~~Definitely not Bluebird though; last time I checked, that thing was monstrous.~~

@bucaran I think it's worth playing with this.

**Comment by Akkuma** [comment]
What makes you think bluebird is monstrous? Bluebird itself is fairly well documented and even has lots of good information about writing high performance JavaScript by avoiding some pitfalls.

**Comment by lukeed** [comment]
I could very well be wrong. The last time I sifted thru it was over a year ago.

Looking at it again now, its core pkg is only 18kb... disproves my "monstrous"

**Comment by lukeed** [comment]
Added in #218
