### ISSUE TITLE
Parallel appears to not work

### ISSUE THREAD

**Issue by Akkuma** [lukeed/taskr#179]
I have a simple task of 

```
task.copyManifest = function* () {
  yield this.source('./src/_manifests/chrome/manifest.json').target('./build/chrome');
};
```

I then have a default of 

```
task.default = function* () {
  yield this.start(['copyManifest', 'otherTask'], { parallel: true });
};
```

I see no copying happening. I only see the copy happen when I remove `{parallel: true}`. To verify that the copy is ran I added a `console.log` and that only logs without parallel.

**Comment by lukeed** [comment]
Hey there, 

Parallel tasks are not awaited by Fly itself. They're spawned as completely separate and self-contained tasks. This means that nothing else cares when these tasks are finished, which means nothing external knows when they're done. 

Check out #174 for more information and lemme know if you have more questions.

**Comment by Akkuma** [comment]
The issue is that I'm expecting something to occur and nothing happens, no tasks ever run. The tasks don't seem to actually be spawning and running, otherwise I should see a file copied regardless of no output from fly itself.

**Comment by lukeed** [comment]
@Akkuma you were correct after all. A simple `yield` was overlooked in an merge conflict, which broke the `parallel` behavior.

Thanks!
