### ISSUE TITLE
How to create a plugin contains multiple sub-methods ?

### ISSUE THREAD

**Issue by frantic1048** [lukeed/taskr#183]
I'm trying to transplant gulp-connect to fly, it uses different methods to control server behavior: start, reload and close.

In gulp, they use `connect.server()`, `connect.reload()` to call different methods.

In fly documentation, it didn't mention about a plugin other than a single function. How could I achieve similar behavior in fly ?

Or, I should just put these start/reload/close methods in plugin argument, like `.connect({method: 'start', options: {...}})` ?

**Comment by frantic1048** [comment]
I just took a look at `fly-kit-web` and `browser-sync` . It looks directly usage is fine, may I don't have to wrap such tool as a plugin ?

**Comment by lukeed** [comment]
Nope, I've been using browserSync for months now & haven't lacked anything.

**Comment by frantic1048** [comment]
Great! Now I'm clear what to use. This issue seems not so necessary now.
