### ISSUE TITLE
Process.chdir impacts code outside of Fly

### ISSUE THREAD

**Issue by Akkuma** [lukeed/taskr#186]
I wrote a library that basically allows integration of web extensions within other web extensions and handles the heavy lifting of merging the child extensions into the parent. The first child extension to leverage this uses Fly and fly uses [`process.chdir`,](https://github.com/flyjs/fly/blob/28f9ce85fca4039b3b405330028772a978ae7648/lib/fly.js#L73) but never reverts it once its work is done. This impacts other code that expects `process.cwd` to remain correct.

There are two options that spring to mind. One retain a reference to the original `process.cwd` and switch back after tasks are ran. Two future don't change cwd, but pass along "cwd of fly" to code that requires it.

**Comment by lukeed** [comment]
@bucaran Wtf does "++" mean? These new labels are SO jarring. Caps for the loss 💀

**Comment by ghost** [comment]
Changed enhancement for ++. What do you want to call it? (Other than enhancement.)

**Comment by lukeed** [comment]
@bucaran imo, (please) leave everything lowercase. And `++` ==> `feature`, `?` ==> `maybe`

**Comment by ghost** [comment]
@lukeed Sorry, I missed your reply. I'm fine with your name changes. I kinda like the names in uppercase, but you can make them lowercase if you prefer. 🙇

**Comment by hzlmn** [comment]
@lukeed What was the original purpose of `process.chdir`? I can't see any code dependent on `process.cwd`.

**Comment by lukeed** [comment]
@hzlmn I think it was to stay true to the `this.root` value, so that pathing & targeting worked correctly. Tbh, I'm not sure if it's still doing anything useful.
