### ISSUE TITLE
Not very informative message, when flyfile.js not found

### ISSUE THREAD

**Issue by hzlmn** [lukeed/taskr#192]
The problem is with `cli.spawn` method, that not handle `null` exception.
Fly instance should emit `flyfile_not_found` event to properly show error message.

![2016-08-18 12 04 33](https://cloud.githubusercontent.com/assets/8246283/17769274/86a3f0de-6540-11e6-9fba-89ec42df8b6f.png)

Btw, fixing it. Gonna submit PR later in the evening.

**Comment by ghost** [comment]
Is this fixed?

**Comment by lukeed** [comment]
@bucaran It is, but not merged yet. Waiting on @hzlmn to send a quick fix on the PR.
