### ISSUE TITLE
Fly.rename unfound

### ISSUE THREAD

**Issue by hzlmn** [lukeed/taskr#196]
From examples

``` js
exports.default = function * () {
    yield this
        .source('hello')
        .rename('bye')
        .target('')
}
```

Did you drop this method, or how renaming should be done?

Also what if I want to specify target file instead of folder like

``` js
exports.default = function * () {
    yield this
        .source('src/index.js')
        .transform()
        .target('dist/changed.js') // here I want to rename file after transform
}
```

@lukeed :question:

**Comment by lukeed** [comment]
Hey, rename hasn't been in Fly since before I joined the project. 

Instead, you use `concat`. It's probably not the most sensible api but it does what it's supposed to.

If you concat a single (or glob) file before `target`, then that becomes the destination filename.

**Comment by hzlmn** [comment]
@lukeed Thanks
