### ISSUE TITLE
Windows: `target` directory contains nested `source` directory

### ISSUE THREAD

**Issue by devmondo** [lukeed/taskr#200]
hi, 

awesome project, i just faced little issue, with the below code, Fly creates `src` as sub dir of `dist` but i dont want that, what i want is to replicate same structure of `src` just under `dist`

```
const paths = {
    scripts: ['./src/**/*.js']
}

export default async function () {
    await this.watch(paths.scripts, 'babel');
}

export async function babel() {
    await  this.source(paths.scripts)
        .babel({
            presets: [["es2015", {"loose": true, "modules": false}], "stage-1", "stage-3"],
            plugins: ["transform-es2015-modules-commonjs",
                ['transform-runtime', {
                    "polyfill": false,
                    "regenerator": true
                }]
            ],
            sourceMaps: true
        })
        .target(`dist`)
}
```

**Comment by hzlmn** [comment]
What version of `Fly` do you use? I can't reproduce this case

**Comment by devmondo** [comment]
thanks for prompt response, 

version 1.3.1
Windows 10

**Comment by hzlmn** [comment]
I will look on this at home on Win machine, seems weird. Maybe some problems on win with glob matching.

**Comment by lukeed** [comment]
I ran into this as well a few days ago. It's definitely a bug on windows only. Our node path handling isn't consistent, but I haven't had time to go thru and find the culprit yet.

**Comment by lukeed** [comment]
Solved. 

Node's `path.sep` constant is `\`, even though the OS handles `/` just fine. What happened was that `expand` and `unwrap` were always returning file paths with the `/` notation, I guess because it's "universal"?

So, when it came time to trim/parse/resolve the `target` path, the expanded `filepath`s (containing `/` only) could not be `split` by `\`.

**Comment by devmondo** [comment]
thank you :)
