### ISSUE TITLE
Use Type Checker?

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#214]
Either [Flow](https://flowtype.org/) or [Typescript](https://www.typescriptlang.org/).

(cool [flow plugin](https://github.com/amilajack/eslint-plugin-flowtype-errors). im sure there are others)
#### Pro
- Informed source
- catch things our (current) tests won't
#### Con
- Requires compile step before build
- Stack tracing is slightly problematic (minified vs transpile bloat)

**Comment by hzlmn** [comment]
Strong plus from my side for `Flow`, basically it will be a good combo with 

> Rewrite with supported ES2015 features https://github.com/flyjs/fly/issues/203

**Comment by lukeed** [comment]
I decided not to use Flow in order to stay true to the "lightweight" mission of Fly. 

Although it wouldn't affect user downloads, it adds a couple of extra steps to the process, which then opens the door for more... then more... in the future. Then Fly would end up in the same mess it was when I came aboard.

IMO, for now, keep _everything_ as lean as possible. If something arises that demands a compile step, then we'll add Flow in at that time.

**Comment by jorgebucaran** [comment]
@lukeed Not the same, but while we're talking about types, what about adding a type definition file for the API.

**Comment by lukeed** [comment]
@jbucaran Howdy! Sure, not opposed to that.

**Comment by hzlmn** [comment]
@lukeed  Would you like to add type definitions for `Flow` and `Typescript`, or can I ?

**Comment by lukeed** [comment]
@hzlmn @jbucaran Let's wait until #229 is resolved. That still poses a threat to rewriting the current API... perhaps drastically (but I hope not).

I'm hoping to spend this weekend and/or next weekend on finding a good solution.

**Comment by hzlmn** [comment]
Ok, got it.

**Comment by hzlmn** [comment]
@lukeed Seems like API pretty stable, should we add definition files 🤔?

**Comment by lukeed** [comment]
Sure, go for it! I don't use TS so forgot about this.
