### ISSUE TITLE
Add 2.0 documentation

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#221]
1. update & move all past examples to an `examples` branch
2. update & move `CONTRIBUTING` and `CHANGELOG` to "Wiki" section
3. update `master`'s `readme.md` content. 
   - point to Wiki
   - point to Examples
4. Move previous (secondary) `README-{lang}` docs to "Wiki"

(benchmark?)

**Comment by dkebler** [comment]
current documentation link on flyjs readme.md and it's wiki is broken
https://github.com/flyjs/fly/blob/master/docs/README.md
looks like you moved the doc folder elsewhere

**Comment by lukeed** [comment]
Yup. It's all getting sorted locally for now. If you're looking for 1.4 documentation, you have to [traverse the tags](https://github.com/flyjs/fly/tree/v1.4.1/docs).
