### ISSUE TITLE
time to run task keep increasing

### ISSUE THREAD

**Issue by devmondo** [lukeed/taskr#223]
hi,

with this below time keep increasing with each compile step so it starts with 200 ms and keep going up to 1 second, 2 seconds,etc...
i checked to see if only one files is passed and indeed it is

```
const paths = {
    clientScripts: [`src/client/**/*.js`],
    serverScripts: [`src/server/**/*.js`],
    html: `src/client/**/*.html`
}

let babelOptions = {
    presets: [`es2015`, `stage-1`, `stage-3`],
    plugins: [`transform-es2015-modules-commonjs`,
        `transform-decorators-legacy`,
        // `transform-es2015-typeof-symbol`,
        `typecheck`,
        `syntax-flow`,
        `transform-flow-strip-types`,
        [`transform-runtime`, {
            "polyfill": false,
            "regenerator": true
        }]
    ],
    sourceMaps: `inline`,
    sourceRoot: `./`
}

export default async function () {
 await this.watch(paths.clientScripts, `clientJs`);
}

export async function clientJs(file) {
    let source = file ? file : paths.clientScripts;
    let target = file ? `dist/` : `dist/client/`;
    await  this.source(source)
        .babel(babelOptions)
        .target(target);
}
```

**Comment by lukeed** [comment]
Hi @devmondo. Unfortunately with `2.0` right around the corner, I won't be supporting `1.4.x` anymore.

Fly `2.0` is a massive improvement in many ways. It's only in `beta` still because I'm upgrading "essential" plugins to the `2.0` syntax.

Hope it's not too much of a bother in the interim.

**Comment by devmondo** [comment]
@lukeed thank you very much for the always prompt support :)
i am waiting eagerly for `2.0` hope it is coming soon !

**Comment by lukeed** [comment]
@devmondo Let me know a list of plugins you're actively using (besides babel) and I'll let you know when those have been converted.

**Comment by devmondo** [comment]
@lukeed thanks man, nothing special really 
- babel (plugin)
- browsersync( which i am using manually without plugin)
- nodemon( which i am using manually without plugin)
- Fly's concat

besides above i dont have anything special and everything is working fine except this slow time and windows path issue here #216

**Comment by lukeed** [comment]
@devmondo Ah, then you can actually go ahead and start using fly@beta; the only real difference is that `.concat` got [moved to its own plugin](https://github.com/lukeed/fly-concat).

**Comment by lukeed** [comment]
@devmondo Oh, and passing files to tasks changed a bit too. (There will be an upgrade guide -- haven't gotten to it yet).

``` js
exports.default = function * () {
  yield this.watch(globs, ['task1', 'task2']); // <= will be ran serially
};

exports.task1 = function * (o) {
  // o.val: any returned (or initial) value
  // o.src: a single FILE PATH, via .watch() ****
  yield this.source(o.src || 'src/foo.bar')
    .babel().target('dist');
}
```

**Comment by devmondo** [comment]
@lukeed 

i uninstalled `fly` and `fly-babel` and installed `fly@beta` and `fly-babel` again and here is my code below

```
const paths = {
    clientScripts: [`src/client/**/*.js`],
    serverScripts: [`src/server/**/*.js`],
    html: `src/client/**/*.html`
}

export default async function () {
    isWatch = true;
    isProd = false;

    await this.watch(paths.clientScripts, [`clientJs`]);
    await this.watch(paths.serverScripts, [`serverJs`]);
}

export async function clientJs(o) {
     await  this.source(o.src || o.val)
        .babel(babelOptions)
        .target(target);

}

```

maybe i am doing something wrong, but i get this error

```
TypeError: this.filter is not a function
  -     at Fly.module.exports (C:\projects\test\node_modules\fly-babel\index.js 9:15)
```

**Comment by hzlmn** [comment]
@devmondo `fly-babel` currently written in old manner (not for `v2`). Basically `API` for plugins changed a little bit with `v2`. Luke will fix it soon I think.

**Comment by devmondo** [comment]
@hzlmn  thanks for explanation man

**Comment by hzlmn** [comment]
@devmondo My bad, Luke has already changed it [here](https://github.com/flyjs/fly-babel/blob/master/index.js)
but seems like not released. If you want to try it right now, you can just install module from `git`

**Comment by devmondo** [comment]
@lukeed @hzlmn thank you

installing `fly-babel` through get made things work but only using the `generators` `yield` syntax, using `async/await` syntax gives an error `task is not a function`.

and i traced down the time accumulation issue, it is webstorm, i guess there is some kind of conflict between it and the filewatcher used in `fly`?

**Comment by hzlmn** [comment]
@devmondo Could you give a stacktrace, or better a screenshot of this error ?

**Comment by devmondo** [comment]
@hzlmn sure

```
stack:
    - TypeError: task is not a function
-     at Fly.<anonymous> (C:\projects\test\node_modules\fly\lib\api\start.js 42:16)
-     at undefined.next (native)
-     at undefined.tryCatcher (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\util.js 16:23)
-     at PromiseSpawn._promiseFulfilled (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\generators.js 97:49)
-     at Fly.start (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\generators.js 201:15)
-     at Fly.<anonymous> (C:\projects\test\node_modules\fly\lib\boot.js 6:12)
-     at C:\projects\test\node_modules\fly\lib\api\serial.js 13:22
-     at undefined.next (native)
-     at undefined.tryCatcher (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\util.js 16:23)
-     at PromiseSpawn._promiseFulfilled (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\generators.js 97:49)
-     at C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\generators.js 201:15
-     at tryCatcher (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\util.js 16:23)
-     at Object.gotValue (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\reduce.js 157:18)
-     at Object.gotAccum (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\reduce.js 144:25)
-     at Object.tryCatcher (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\util.js 16:23)
-     at Promise._settlePromiseFromHandler (C:\projects\test\node_modules\fly\node_modules\bluebird\js\release\promise.js 510:31)
message: task is not a function
```

```
export default async function () {
    await this.watch(paths.clientScripts, ['clientJs']);
};

export async function clientJs(o) {
       await this.source(o.src || paths.clientScripts)
        .babel(babelOptions)
        .target('dist/client/');
 }
```

**Comment by hzlmn** [comment]
@devmondo interesting... will look on this at home.

**Comment by devmondo** [comment]
@lukeed thanks a lot for the update 
as mentioned here https://github.com/paulmillr/chokidar/issues/445#issuecomment-193290880
can we pass option to chokdir ?

and have a great weekend guys :)

**Comment by lukeed** [comment]
@devmondo Can you try setting it to `true` locally & let me know how it goes? You're running Win _and_ Webstorm, both of which I can't use right now.

A la `chokidar` repo: 

```
CHOKIDAR_USEPOLLING=1 npm run fly
```

**Comment by devmondo** [comment]
@lukeed holy god!!!! it went from 1 second to 200 - 250 ms stable!!!!!! and i made sure to modify file and save it multiple times aggressively. so yeah your suggestion works!

**Comment by lukeed** [comment]
@devmondo hahaha, good!... I'll look into it more. Not sure (yet) if `usePolling` should **always** be `true` on Windows, or if it's just your Webstorm + Windows environment.
