### ISSUE TITLE
Website for Fly ✈

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#23]
Draft for the website below.

![fly_site](https://cloud.githubusercontent.com/assets/8317250/8567900/ea733b70-25a3-11e5-80f4-07a7883599db.png)

**Comment by bucaran** [comment]
![fly_site2](https://cloud.githubusercontent.com/assets/8317250/8568368/0777d68c-25a8-11e5-977a-65fe866d97c0.png)
<hr>
![fly_site3](https://cloud.githubusercontent.com/assets/8317250/8568369/0b321eb8-25a8-11e5-81c6-4d131b68fb61.png)

**Comment by bucaran** [comment]
I am not so sure about the colors of the second one, but I feel is in the right direction?

@flyjs/developers ?

**Comment by hzlmn** [comment]
I like first one

**Comment by bucaran** [comment]
@drKraken  What about this one? or still first one?


![fly_site3](https://cloud.githubusercontent.com/assets/8317250/8568556/9e3e4d16-25a9-11e5-8abf-dc6b9c01cba5.png)

**Comment by ghost** [comment]
Me too, let's go with that one.

**Comment by hzlmn** [comment]
@bucaran it's interesting too, maybe connect top layer with a bottom layer for 3d-like feeling?

**Comment by ghost** [comment]
Let's keep it simple for now :smile:

**Comment by hzlmn** [comment]
@bucaran ok :space_invader:

**Comment by ghost** [comment]
@drKraken Thanks!

**Comment by yang-wei** [comment]
:+1:

**Comment by ghost** [comment]
@TrySound @watilde ?

**Comment by watilde** [comment]
Wow seems cool and simple. +1 from me too:)

**Comment by mathieumg** [comment]
Looks good!

**Comment by ghost** [comment]
@drKraken How are things coming? :smile:

**Comment by hzlmn** [comment]
@bucaran sorry man, have some tasks at work, so not yet fixed what we discussed, but i can push early version without in-site plugin search..

**Comment by bucaran** [comment]
No prob. Take your time :smile: 

Looking forward to it though

**Comment by bucaran** [comment]
@drKraken Ping.

**Comment by bucaran** [comment]
Hey @drKraken, any chance we have something this week?

**Comment by ghost** [comment]
@drKraken Ping! :smile:

**Comment by iamstarkov** [comment]
I think @drKraken has no time for this

**Comment by visualcookie** [comment]
Looks like it.

**Comment by bucaran** [comment]
@drKraken You could totally push your early version anytime and we can continue to improve it over time. No need to have the full definitive version before committing to the repo IMO :smile:

**Comment by ghost** [comment]
@drKraken Push what you have when you can and we'll take it from there! No worries and thanks.

**Comment by ghost** [comment]
@drKraken Do you have time to push what you were able to come up during the time you worked on the website? Thanks.

**Comment by tomByrer** [comment]
Suggestion: Make a separate website repo.

**Comment by ghost** [comment]
@tomByrer Hey. Yeah, there used to be one. But the website idea never really took off :sweat_smile:

**Comment by visualcookie** [comment]
@bucaran Y not? Did the guy that made it before had no more time? Just curious, because I think here are several others that would take over his work. :P

**Comment by ghost** [comment]
Yes, more or less and I was busy with fly itself at the time. 

If anyone wants to take a stab be my guest, we have the domain and everything, [flyjs.io](http://flyjs.io).

Now, there is no design at the moment (let's say I kind of grew cold to the one above), but if someone is really interested in working on this, I'll come up with a new one.

**Comment by denysdovhan** [comment]
I am not so busy these days, so I could help with site. However, I don't understand completely what's wrong. Aren't there people to finish work with the site, right?

**Comment by lukeed** [comment]
@bucaran I could have completed it by now but you wanted me to wait for a design from you first,  so I held off because I didn't want to be rude and take over :)

**Comment by ghost** [comment]
Ah, yeah, I forgot to mention @lukeed totally wanted to take over this. Great! Now that we have people on board, I'll come up with something and post it here.

**Comment by ghost** [comment]
Closing in favor of #158
