### ISSUE TITLE
Save context after `fly.target`

### ISSUE THREAD

**Issue by hzlmn** [lukeed/taskr#231]
Hi, could we save context of file object after finally written it with`fly.target` ?
For examples I have task `scss` and want to compile it to `css` and write to file.
```js
yield this
  .source('./src/**.scss')
  .sass()
  .target('./build')
```
but when I need to make one extra step after target - `data` param is lost 
Example: 
```js
yield this
   .source(files)
   .sass()
   .target('./build')
   .minify()  // here i want to minify compiled content 
   .concat('test.min.css')  // concat to single file
   .target('./build')   // and then write back to build dir
```

**Comment by hzlmn** [comment]
Right now for same task I use `this.$.write` and internal `this._.files` array, that seems more like a hack.

**Comment by lukeed** [comment]
This is a simple fix. 👍 I had it in mind at the beginning but forgot to ensure it was achievable.
