### ISSUE TITLE
Add `fly.imports` key to `package.json` config

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#234]
Pulled from #233 

For the sake of reusable, private plugins:

```json
{
  "fly": {
    "imports": [
      "./build/custom-task-one.js",
      "./build/custom-task-two.js",
      "./build/custom-task-three.js"
    ]
  }
}
```

```js
// build/custom-task-one.js
module.exports = function () {
  this.plugin('plugOne', {every: 0}, function * (files, opts) {
    // custom stuff
  })
}

// flyfile.js
yield this.source('src').plugOne({hello: 'world'}).target('dist');
```

---

Open to alternative names for the `imports` key.

The same functionality can be achieved using `npm link` (or `npm install` and `file:./` as a dependency), but this requires that each plugin has its own `package.json` file.

> You _can_ group multiple plugins in the same "package" ([example](https://github.com/flyjs/fly/issues/233#issuecomment-258652507)). However, this method also doesn't scale well & becomes quite messy to manage.

**Comment by devmondo** [comment]
@lukeed love this!!! configuration based,

`imports` is fine, if i may suggest also may call them`local-extensions`,  `local-plugins`, `local-tasks` or just omit the `local` part

**Comment by lukeed** [comment]
@devmondo thanks!

As mentioned in #233, I want to stay away from calling it `plugins` only because it implies that you can declare public packages there too. So, there, I used `localPlugins`

**Comment by devmondo** [comment]
@lukeed awesome, i noticed you call them above `task` it is good too and i agree with you about your concern, i think `require` too is a good candidate this goes along with `Node` convensions

**Comment by lukeed** [comment]
> i noticed you call them above task it is good too 

@devmondo sorry, what do you mean?

**Comment by devmondo** [comment]
`// build/custom-task-one.js`

**Comment by lukeed** [comment]
Oh, sorry. I meant `custom-plugin-*.js`. This new keys is **only** for plugins.

Tasks can already be shared easily from within a flyfile. 

``` js
exports.default = function * () {
  // example "custom" task
};

exports.styles = require('./tasks/styles');

exports.scripts = require('./tasks/scripts');
```

**Comment by devmondo** [comment]
man lovely!!! i cant wait for this to be released

**Comment by lukeed** [comment]
The key is called `requires`.

``` json
{
  "fly": {
    "requires": [
      "./build/custom-plugin-one.js",
      "./build/custom-plugin-two.js",
      "./build/custom-plugin-three.js"
    ]
  }
}
```

**Comment by devmondo** [comment]
awesome!!!!!

**Comment by lukeed** [comment]
@devmondo You can now access this by installing the latest `beta` release.

**Comment by devmondo** [comment]
@lukeed  it is working perfectly!!!!! thank you very much

**Comment by lukeed** [comment]
@devmondo Yippee! 🙌🏼
