### ISSUE TITLE
using async await with v 2.0

### ISSUE THREAD

**Issue by devmondo** [lukeed/taskr#238]
Hi,

can we start using it now or not yet :)

**Comment by lukeed** [comment]
Yo!

Using `async`/`await`? [Yes](https://github.com/lukeed/fly-esnext). 

I'm still trying to figure out a good way for `fly.parallel`... that's the only thing holding Fly in `beta`.

**Comment by lukeed** [comment]
As long as you don't have any syntax errors (follow the examples; accepted syntaxes are flexible enough), `fly-esnext` rewrites the flyfile "behind the scenes". :)

**Comment by devmondo** [comment]
@lukeed  thanks mate for the update :)

**Comment by lukeed** [comment]
@devmondo You bet. The parallel bit has been making me mad, but I don't want to push out a faulty version. It's kinda largest feature.

**Comment by devmondo** [comment]
@lukeed hope it would be fixed soon, Fly is sooooooooooo fast, simple and i replaced all my Gulp tasks with it :)

**Comment by lukeed** [comment]
🏃💨

**Comment by devmondo** [comment]
`Fly` 💨 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      `The Rest` 🐌

**Comment by lukeed** [comment]
hahah
