### ISSUE TITLE
unexpected import token

### ISSUE THREAD

**Issue by devmondo** [lukeed/taskr#239]
Hi,

all of a sudden i get this error and i cant run `Fly`

i have latest `2.0.6` beta and i also have `fly-esnext`.

i never got this error before and i dont know why it happened now!

for now i temporarly changed `import` with `require`

thanks in advanced.

**Comment by lukeed** [comment]
Hey bud, just got home and it's too late for me to look into this, but I will first thing in the morning!

In the meantime (if you see this) please upload the flyfile.js you were trying to use, as well as the package.json contents. I'll need these to figure out what happened. 

Thanks

**Comment by devmondo** [comment]
@lukeed  mate,

thanks for the reply :)

i cant upload this stuff as it is internal, but you know it is really simple, just put this one line of code in `flyfile`
`import * as fs from 'fs'` and you will get the error.

i also got another colleague who face the same issue it is only when he created new project, it seems his current project works fine, so i doubt there is something hanging in node cache that makes it work, but again once you create new project and install `fly` and `fly-esnext` you get the above error 
i think it is same as this issue here [import problem](https://github.com/flyjs/fly/issues/159#issuecomment-208233654)

please let me know if i can send package.json in private or something if it helps

thanks

**Comment by lukeed** [comment]
Oh, that's the problem. The `fly-esnext` package uses simple regex patterns to rewrite parts of es6 back to es5.

Unfortunately, the `* as` and `{ thing }` aren't included. I'm not opposed to including them, it's just harder to do so.

For now, only the examples included in its Readme are doable. Sorry =/

**Comment by lukeed** [comment]
@devmondo I've [created an issue](https://github.com/lukeed/fly-esnext/issues/5) in the `fly-esnext` repo. I'll close this now, but you can track its progress there. 

Please use `require()` statements for the time being. Thanks & sorry!
