### ISSUE TITLE
Remove magic `this` from tasks

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#243]
Tasks will lose access to `this` during definition.

What used to be:

```js
exports.default = function * (opts) {
  yield this.source(opts.src || 'src/**')...
}
```

Now looks like this:

```js
exports.default = function * (fly, opts) {
  yield fly.source(opts.src || 'src/**')...
}
```

> **Note:** The `opts` param is conditionally populated in both cases. This is already an implemented behavior.

#### Need Feedback

For `2.0`, I think users should still have access to `this` but it will not be documented or encouraged. 

Then in `3.0`, the binding to `this` will be removed entirely.

---

cc: @jbucaran  @rauchg

**Comment by jorgebucaran** [comment]
Nice. Why not entirely removing the binding when 2.0 is released? We could drop node 4.6 by then as well.

**Comment by lukeed** [comment]
We could. Only hesitation is that it breaks all past `flyfiles`. There should probably be a grace period, despite the fact that it's easy to _upgrade_.

**Comment by jorgebucaran** [comment]
It's fine then. 2.0 is still too soon before I can come up with anything as discussed in #241.

I am going to be toying with this today for a bit!

**Comment by lukeed** [comment]
@jbucaran Already solved this. Opened issue just for tracking.

**Comment by jorgebucaran** [comment]
Great! I am going to be toying with #241. I'll update that issue to clarify.

**Comment by rauchg** [comment]
This is fantastic

**Comment by devmondo** [comment]
Awesome!!!
