### ISSUE TITLE
extract `fly.watch` to plugin

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#245]

**Comment by lukeed** [comment]
As noted in the commit's comment:

* Total time taken for tests execution dropped by 60% !!!

cc/ @jbucaran @hzlmn

**Comment by jorgebucaran** [comment]
@lukeed What do you mean? `watch` is still something I imagine end users will want to do anyway. No?

EDIT: [Nevermind](https://github.com/flyjs/fly/issues/245#issuecomment-272054743) ;)

**Comment by lukeed** [comment]
Yes, but not all. Now it's installed via `fly-watch`. I thought we both agreed on this [yesterday](https://github.com/flyjs/fly/issues/241#issuecomment-271745846).

**Comment by jorgebucaran** [comment]
About separating fly.watch into its own plugin, I agree.

What I realize now, is that 60% test exec drop refers to fly tests, which for reason I misinterpret as tasks running 60% faster.

**Comment by lukeed** [comment]
Ah, yeah. I made that optimization a long time ago, wherein `chokidar` became lazy-loaded instead of eagerly loaded so that only those who actually ran `fly.watch` loaded up Chokidar.

We got same perf boost there too.

I'll link to that commit when I get back to computer.

**Comment by lukeed** [comment]
@jbucaran for reference: 12ec1a3edcbf4402b080f49cd3974f04d73cf4ce and #236
