### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by jorgebucaran** [lukeed/taskr#247]
## Suggestions

* bluebird is fast, that's the thing right?

* Instead of globby, node-glob should be enough.

* We could probably drop prettyjson and the prettylog with its crappy regex which has not changed much since I wrote it

* Arrify is ridiculous. 

* Let's get rid of update-notifier and do nothing instead.

* I'd like to use clor, instead of chalk. No biggie here, but a personal preference.

* flatten is fine for now, but would like to revisit this, either pick another library, or find a way to not need to flatten arrays. 

* We can drop dev deps like tap-spec. As long as the test output is tap, it's fine.

* I don't find linters much useful nowadays. I think fly could do without xo, but this is not a priority.

## List

- [x] globby
- [x] flatten
- [x] prettyjson
- [x] arrify
- [x] update-notifier
- [x] chalk->clor

**Comment by lukeed** [comment]
Keeping `tap-spec`, `xo` and `flatten`.

Would prefer to keep `update-notifier`.

We can probably drop bluebird when node 8 becomes stable. TBD

Let's worry about clor vs chalk after 2.0. As I've mentioned, I have no preference so long as clor is cross compatible. (Not using `clor/c`)

The rest I can do without.

**Comment by jorgebucaran** [comment]
Why not using clor/c? It's optional.

What's the big deal about `update-notifier` anyway?

**Comment by lukeed** [comment]
Yea, I know it's optional. Just prefer the current pattern.

We have a lot of users who use Fly globally. Much harder for them to keep track of updates without it.

**Comment by jorgebucaran** [comment]
It was probably my mistake if I tried to emulate gulp. It was probably easier to test run things with a global fly in the beginning too. 

Anyway, using fly globally should be *discouraged* IMO.

**Comment by lukeed** [comment]
Gotcha. I agree, I never think Fly is a good idea for global use. But shouldn't we at least notify `1.x` users that `2.0` is out?

**Comment by jorgebucaran** [comment]
Ok, let's revisit update-notifier in the future and keep this issue to track the avada kedavra of the other deps. I'll create another issue in due time wrt to the switch to 🌈 clor.

EDIT: I've assigned myself, so you don't need to worry about this for now.

**Comment by lukeed** [comment]
Haha okay. I'm taking care of `arrify` and `globby` now. I'm also editing this task to become a checklist.

**Comment by lukeed** [comment]
I went ahead & remove `update-notifier`. I went back & counted our global-related issues and it wasn't as many as I thought.
