### ISSUE TITLE
Bluebird's optimization "rules"

### ISSUE THREAD

**Issue by hzlmn** [lukeed/taskr#252]
As `fly` heavily use `bluebird` I think it would be a good idea, to look through code and fix common optimization blockers at least that described [here](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers)

**Comment by lukeed** [comment]
Correct! This was going to be my final step before releasing.

Most of these are just V8 engine optimizations and not specific to Bluebird itself. The main one that will be changed is our `for-of` loops.

**Comment by hzlmn** [comment]
@lukeed Ok, cute
