### ISSUE TITLE
Accept `opts.func` for Plugin API

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#253]
Current: **plugin(name, opts, func)**

The `func` parameter should be read as the fallback.

```js
func = opts.func || func
```

This allows for cleaner plugin (inline & external) definitions; especially if relying on the default `every` and `files` settings.

```js
// external
this.plugin('myName', {
  files: true,
  every: false,
  *func(arr) {
    // `arr` is all files
  }
})

// external w/defaults
this.plugin('myName', {
  *func(file) {
    // loop each `file` object
  }
})

// inline w/defaults
exports.fooTask = function * (fly) {
  yield fly.source('foo/*').run({
    *func(file) {
      // loop each `file` object
    }
  }).target('bar')
}
```

Reference: https://github.com/flyjs/fly/issues/233#issuecomment-274749015

**Comment by lukeed** [comment]
Now that I see this, external plugins should also accept a `name` key. 

Doing so will convert the API to **plugin(opts, [func])** for _both_ inline & external plugins.

```js
// external
this.plugin({
  name: 'myName',
  files: false,
  every: false,
  *func(arr) {
    // `arr` is all globs
  }
})

// external w/defaults
this.plugin({
  name: 'myName',
  *func(file) {
    // loop each `file` object
  }
})
```

**Comment by jorgebucaran** [comment]
@lukeed Good new, but can you clarify:

> This allows for cleaner plugin (inline & external) definitions; especially if relying on the default every and files settings.

How does it make it cleaner? The examples, I think, show the new syntax. Can we get an example using the older / less clean syntax?

**Comment by lukeed** [comment]
> Current: **plugin(name, opts, func)**

```js
this.plugin('nyName', {every: false}, function * (files, opts) {
  // files: all file objects
  // opts: user options
});
```

**Comment by jorgebucaran** [comment]
@lukeed Thanks.

**Comment by lukeed** [comment]
@jbucaran No problem. So what do you think on the newer suggestion? 

It also could mean for simpler external plugins (aka, installed via NPM):

```js
// current
module.exports = function () {
  this.plugin('myName', {every: false}, function * (files, opts) {
    // files: all file objects
    // opts: user options
  });
}

// with proposed change
module.exports = {
  name: 'myName',
  every: false,
  *func(files, opts) {
    // files: all file objects
    // opts: user options
  }
}
```

---

cc: @devmondo @hzlmn @watilde

**Comment by jorgebucaran** [comment]
@lukeed Proposed style is easier to not mess up, since you don't need to remember that name comes first, etc.
