### ISSUE TITLE
Community Plugins needing TLC

### ISSUE THREAD

**Issue by Swizz** [lukeed/taskr#261]
As proposed by @jbucaran.

Follows the #260 discussion, but proclaims the real subject.

**Comment by lukeed** [comment]
Scoped packages are now enabled & parsed by Fly.

This issue should be a list of community packages that need updating. 

If you find a Fly plugin that is outdated or seems to be neglected:

1) Post a link to the repository here
2) Open an issue in the plugin's repository in attempt to contact the author
3) Fork & submit a PR if you can 😄 

Forked repositories can (and sometimes should) be published as a [scoped package](https://docs.npmjs.com/misc/scope#publishing-scoped-packages).

> **Note:** Don't forget the `--access public` flag!

**Comment by Swizz** [comment]
Will not use @fly scope only on officially maintained packages ?
(I mean part of the fly org or by a fly core contributor)

**Comment by lukeed** [comment]
No, scopes should only be used if there are name conflicts.

**Comment by hzlmn** [comment]
@lukeed Are there any reasons for not using @Swizz 's style for official packages, i mean making them scoped?

**Comment by lukeed** [comment]
I believe that all affected packages will break when existing users go to download them. This sorta thing should have been done before/with 2.0 launch.

**Comment by Swizz** [comment]
Publish under both name and scoped.
Use [npm-deprecate](https://docs.npmjs.com/cli/deprecate) to claim the new scoped format ?

**Comment by lukeed** [comment]
Sure. I don't mind doing that. However, I'm still waiting on @jbucaran to grant me NPM access for nearly all the org repos. 🙏 One can only ping so many times.

**Comment by jorgebucaran** [comment]
@lukeed I'll get around that this week. 🙇 👋

**Comment by lukeed** [comment]
lol 🤐 What about `fly-coffee` very quickly so that @hzlmn can use it?

**Comment by hzlmn** [comment]
@lukeed Man, I don't use coffeescript, it was just for example :laughing:

**Comment by lukeed** [comment]
Oh, haha. Well, now it's 1.0 anyway...

**Comment by pine** [comment]
Hi. Should I move some my fly-* repositories to the organization what I am managing ? And, do you think other people's repositories should do so 🤔 

I think that it is best to be properly maintained ☺️

**Comment by jorgebucaran** [comment]
I think that'd be the way to go.

@lukeed Waiting for npm to reply on a thing, then I'll add you all to the repos, soon! 🙏

**Comment by Swizz** [comment]
Finished some days ago the [fly-serve ](https://github.com/Swizz/fly-serve) plugin, can I ask for some code reviews ?

**Comment by lukeed** [comment]
Hi @Swizz I've left a "code review" for you in https://github.com/Swizz/fly-serve/pull/2 👍

**Comment by lukeed** [comment]
Closing as Taskr now offers official packages via the scoped `@taskr` namespace! 🎉 Thanks @Swizz and @hzlmn for the idea -- moving to "Taskr" was the perfect time to introduce this.

We will also be maintaining a list of community plugins on the root README 👍 

Thanks all 🙌
