### ISSUE TITLE
Flatten files at destination

### ISSUE THREAD

**Issue by dredzone** [lukeed/taskr#262]
How to flatten directories when when copy files? 
target(dir, {depth: *}), depth option has no effect in version 2^.

**Comment by lukeed** [comment]
That is correct. The `depth` option from `fly.target` was removed in v2. 

It now exists as a separate package ([`fly-flatten`](https://github.com/lukeed/fly-flatten)) for those who need it.

> Thanks for the issue. You reminded me that I needed to release this plugin. 😄

**Comment by dredzone** [comment]
thanks for looking, but issue is still there, and I think it's related to task.target and glob replacement,

below is example 
```javascript
yield fly
  .source("jspm_packages/npm/font-awesome*/fonts/*.{woff2,woff,svg,eot,ttf,otf}")
  .flatten()
  .target("dist/fonts/font-awesome");
```
expected: /dist/fonts/font-awesome/**
output (from above code): dist/fonts/font-awesome/font-awesome@4.7.0/fonts/**

**Comment by lukeed** [comment]
No problem!

Yes, that's actually expected. `fly-target` begins reading from the first instance of `*`. So you'll need to specify the full `font-awesome` string.

```js
yield fly
  .source("jspm_packages/npm/font-awesome@4.7.0/fonts/*.{woff2,woff,svg,eot,ttf,otf}")
  .flatten()
  .target("dist/fonts/font-awesome");
```
