### ISSUE TITLE
Roadmap to 0.2.0

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#27]
- New `parallel` option to run filter application to expanded `glob → files` in parallel (almost 40% faster according to my eye-percent tests). In the future we want to run tasks in parallel as well.
- Finally support for async transformers. This is already implemented and working.
- Support to specify the extension a filter outputs if it was to write a file. Obvious missing feature until now (unless you were only concatenating).
- A task named `main` is no longer treated as the _default_ task. Default tasks are either a task named `default` or the _default_ export from your Flyfile.
- Separate `util.js` from core and put into its own module. This [module is already published](https://github.com/flyjs/fly-util) and **fully tested**.

**Comment by girvo** [comment]
Sounds great, looking forward to it!

**Comment by ghost** [comment]
@girvo Landed fly@0.2.0.
