### ISSUE TITLE
Revert Org Logo

### ISSUE THREAD

**Issue by lukeed** [lukeed/taskr#273]
@jbucaran

**Comment by hzlmn** [comment]
Need to start campaign "Save Fly logo" 😄

**Comment by lukeed** [comment]
Seriously

**Comment by jorgebucaran** [comment]
@lukeed I spent several hours working on the new logo and I am pretty happy with it. I'm not reverting the logo.

**Comment by lukeed** [comment]
You spend hours on every iteration & I always humor you. But at some point it has to stop. I'm asking you for this one to be gone cuz it's quite awful tbh... and you said you were happy with the _last_ one & that that was to be it.

**Comment by hzlmn** [comment]
Agree, it's not totally awful but previous one looked better at least for me. Also it's not ok for prod project imo to change logo each month because it should be recognizable

**Comment by jorgebucaran** [comment]
@hzlmn It's not going to change every month, but it's going to change this time.
