### ISSUE TITLE
New logo and evolution of fly's logo.

### ISSUE THREAD

**Issue by jorgebucaran** [lukeed/taskr#274]
Hi @flyjs's everyone. I've changed the logo of the project (again, and now again).

![fly-1](https://cloud.githubusercontent.com/assets/56996/26271217/fe4c1d7a-3d3d-11e7-925b-5df2d67f1fe3.png)

![0be81080-2c40-11e5-98d2-c634f076ccd7](https://cloud.githubusercontent.com/assets/56996/26271258/6815834a-3d3e-11e7-99fb-a0b8015d5ca0.png)

<br>
<br>
<div align=center>
<img src=https://cloud.githubusercontent.com/assets/56996/26271324/3ba6b3dc-3d3f-11e7-9a20-89c8489e1960.jpg>
</div>
<br>
<br>

<br>
<br><br>
<div align=center>

![fly](https://cloud.githubusercontent.com/assets/56996/26274523/b2a217dc-3d86-11e7-87f1-b3cc24f22cb3.png)

</div>

![fly_bg-white](https://cloud.githubusercontent.com/assets/56996/26810930/875ce450-4aa9-11e7-9cdd-748c90835ba5.png)

Hope you like it.

**Comment by hzlmn** [comment]
Man, what's wrong with you? Just leave it as it is. It is not so important, rather would like to see more new features :)
