### ISSUE TITLE
Consider moving from bluebird to any-promise

### ISSUE THREAD

**Issue by karimsa** [lukeed/taskr#275]
With the consideration of performance, perhaps fly should use any-promise instead of bluebird? That way the natively available promise implementation can be used instead of bluebird when available (since the modern versions of node provide that).

**Comment by jorgebucaran** [comment]
@karimsa Yes, that's on the long-term agenda! For now, Bluebird has superior performance.

See here for more info:

- https://softwareengineering.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

This is not going to be the story forever, so I'll be happy to get rid of bluebird when the time is right! 👍

**Comment by karimsa** [comment]
Thanks for the clarification! The choice to use bluebird makes more sense now.

**Comment by lukeed** [comment]
Yo! Closing this since Bluebird is here to stay until native-Node can match it (or within reason).

Thanks!
