### ISSUE TITLE
Executing tasks in series?

### ISSUE THREAD

**Issue by kokujin** [lukeed/taskr#285]
Hi there, is it possible to execute tasks in series? Any examples tht one can point me to? Thanks

**Comment by jorgebucaran** [comment]
I think you can use [`taskr.serial`](https://github.com/lukeed/taskr/tree/master/packages/taskr#taskrserialtasks-options).

**Comment by hzlmn** [comment]
Hello!
Yes you can use https://github.com/lukeed/taskr/tree/master/packages/taskr#taskrserialtasks-options

**Comment by lukeed** [comment]
Hey!

Yup, we call it [`taskr.serial`](https://github.com/lukeed/taskr/tree/master/packages/taskr#taskrserialtasks-options).

> Edit: LOL all of us

**Comment by kokujin** [comment]
Thanks
