### ISSUE TITLE
Guide to convert Gulp plugins?

### ISSUE THREAD

**Issue by kokujin** [lukeed/taskr#287]
Is there a guide/ tutorial that explains how to convert Gulp plugins? Thanks

**Comment by hzlmn** [comment]
Hi, we have not "official" guide for doing this. `Gulp` has different design based on `streams`, so plugins that takes 100+ LOC in `Gulp` can be easily written in ~20-30 LOC in `Taskr` .

If you are interested in development plugin for `Taskr` you can check source of some lightweight plugin like [`@taskr/babel`](https://github.com/lukeed/taskr/tree/master/packages/babel).  API is pretty straightforward

**Comment by lukeed** [comment]
Hello! No official guide. But most of the time, gulp plugins aren't even using streams. So just gotta look at the source and see how the underlying APIs are being used.

What plugin are you trying to convert? We can always help!

**Comment by kokujin** [comment]
Thanks @lukeed  and @hzlmn, I will take a look at some of the Taskr plugins  to see how I would go about about this issue.

I am trying to convert[ Gulp-Inject](https://www.npmjs.com/package/gulp-inject)  so that my stack would be complete. A drop-in replacement for my present Gulp stack.

**Comment by hzlmn** [comment]
No problems. Just FYI you can use [plugin generator](https://github.com/lukeed/generator-taskr) for quick boot of project skeleton. If you stuck - just ping some of us, will be glad to help.

**Comment by lukeed** [comment]
That looks like a fantastic plugin to learn the Taskr api! 

Going to close this particular issue, but please don't hesitate to ask for help!

If it's your only hindrance from switching & arent able to work on a plugin for now, I can do it for you when i get a moment.
