### ISSUE TITLE
Receive updates in CLI

### ISSUE THREAD

**Issue by watilde** [lukeed/taskr#29]
It's common thing to increase issues arising from using old version of module. How about to put [update-notifier](https://github.com/yeoman/update-notifier) for to be able to receive an update of fly version in CLI?

**Comment by ghost** [comment]
Do you want to work on this?

Currently, we are just passing `notifyUpdates({ pkg })` package.json into the update notifier.

**Comment by watilde** [comment]
Oops, I didn't notice about that it has already integrated just cuz I always update to latest version manually and used it. Sorry, closing as already resolved.

**Comment by ghost** [comment]
:+1:
