### ISSUE TITLE
add taskr-standard

### ISSUE THREAD

**Issue by elmasse** [lukeed/taskr#296]
Hi @lukeed first of all thanks for this great work. I have created a standard lint taskr plugin. github repo: https://github.com/elmasse/taskr-standard and npm: https://www.npmjs.com/package/taskr-standard
Do you mind adding this to the community list? I can submit a PR to add that in the Readme.md if it's ok with you.

Thanks!

**Comment by lukeed** [comment]
Great, thanks!

Feel free to open a PR and add it in :clap:

**Comment by lukeed** [comment]
Closed via 3ef795a449feadd2a5febdaa280d67c23a10f460

**Comment by elmasse** [comment]
Awesome! Thank you! 🙏

**Comment by hzlmn** [comment]
Cute plugin, was in my todo list :) Thanks, @elmasse :+1:
