### ISSUE TITLE
excluding specific file on the task build?

### ISSUE THREAD

**Issue by rpmansion** [lukeed/taskr#299]
I have this folder containing typescript files and I want to build this and exclude some files on the build. How do you do that?

**Comment by lukeed** [comment]
Hey, 

You can pass options to [`task.source`](https://github.com/lukeed/taskr/tree/master/packages/taskr#tasksourceglobs-options) which then get passed into `node-glob`. This means that you can do:

```js
task.source('src/*.ts', { ignore:'src/foo.ts' })
```
