### ISSUE TITLE
Async Await tasks

### ISSUE THREAD

**Issue by radum** [lukeed/taskr#301]
Raising an issue because I don't know where else could I ask this.

Assuming I have this taskfile.js

```js
export default async function (task) {
  await task.clear().start('build');
}

export async function build(task) {
  await task.parallel(['scripts', 'styles']);
  await task.start('uglify');
}
```

I run the build task using

```shell
taskr build
```

1. How do I convert the taskfile.js to use the programmatic option?

```js
const Taskr = require('Taskr');
const taskr = new Taskr({
  tasks: {
  }
});

taskr.start('build');
```

2. Can I use functions that return a Promise as Taskr tasks? If so how, because I can't figure it out.

For example I have a clean function:

```js
function clean(pattern, options) {
    return new Promise((resolve, reject) => {
      rimraf(pattern, { glob: options }, (err, result) => (err ? reject(err) : resolve(result)));
    })
}
```

This sits within its own file and is exported as such. How could I use this to define a taskr task and use it in my workflow?

Thank you.

**Comment by hzlmn** [comment]
Hey!

1. Unfortunately, you can not use `async/await` syntax in programmatic API. You need to use generators and `yield` keyword. More can be found [here](https://github.com/lukeed/taskr/tree/master/packages/taskr#programmatic)

2. If i got your question right, you should wrap your function in `bluebird` coroutine for correct work.

**Comment by lukeed** [comment]
Hey @radum 

Without [`@taskr/esnext`](https://github.com/lukeed/taskr/tree/master/packages/esnext), you can only use `async`/`await` if your version of Node supports it. This means 7.4+ (with flag) or 8.x. 

As @hzlmn said, you can only use the `esnext` package with a `taskfile`. Again, for programmatic usage, your Node version must support `async` natively.

```js
const Taskr = require('Taskr');
const { build, clean } = require('./my-tasks');

function * default(t) {
  yield t.serial(['clean', 'build'])
}

const taskr = new Taskr({
  tasks: { build, clean, default }
});

taskr.start(); // runs "default"
```

For your second question, you can `await` (or `yield`) _any_ `Promise`. Your `clean` task is missing a `return` statement, which means the Promise never leaves the function.

```js
function clean(pattern, options) {
    return new Promise((resolve, reject) => {
      rimraf(pattern, { glob: options }, (err, result) => (err ? reject(err) : resolve(result)));
    })
}
```

Although, I would recommend using the [`@taskr/clear`](https://github.com/lukeed/taskr/tree/master/packages/clear) package instead.

Hope that helps~
