### ISSUE TITLE
NPM Link support

### ISSUE THREAD

**Issue by MadcapJake** [lukeed/taskr#31]
[link](https://docs.npmjs.com/cli/link) allows you to symlink directories into your `node_modules` folder.  You type `npm link` inside your plugin's directory and it creates a symlink into your global node packages directory. Then type `npm link fly-pluginName` inside a test app directory and npm will symlink your plugin into your test app's `node_modules`. 

Due to fly checking `package.json` and that `npm link` does not add anything to  `package.json`, fly does not work with symlinked packages.

Currently, a workaround is `npm install --save  path/to/plugin` or just to add your symlinked package manually with 

``` js
"fly-pluginName": "file:./node_modules/fly-pluginName"
```

I think that [fs.readdir](https://nodejs.org/api/fs.html#fs_fs_readdir_path_callback) might be a solution to searching the `node_modules` directory but I am not sure how it handles directories or how it handles symlinks.

**Comment by ghost** [comment]
Would this interfere with other `fly-*` plugins that could exist inside `node_modules`? Fly looks at your `package.json` for declared plugins not because it's the easiest solution, but because that means the user deliberately installed the plugin via `npm i`.

**Comment by MadcapJake** [comment]
After much thought and gitter discussion, I think that supporting linked plugins is not neccessary.
Here's what I wrote on gitter:

> Yeah that's what I am thinking about, when developing a plugin, what's the easiest/smoothest route to testing a plugin? TBH, npm links might not be all that great because npm link with no argument (when setting a package to be "linkable"), overwrites any globally defined package. It might make more sense to use npm link in a situation where you are going to need to develop multiple applications that reference a specific linked package. But in this case, you'd likely only have one app that will reference the indev fly plugin so I think using just a local path in npm makes more sense.

To add to that, `npm link` is great if you have a multiple indev npm packages that are being developed in consortium but since fly plugins are usually just small packages that rely on stable, production packages, it seems a bit overkill to use `npm link` here.

So if you want to test your plugin, just use npm's local path support: `npm install --save-dev /path/to/plugin`.  It's two commands shorter and it doesn't overrwite any global packages.

**Comment by ghost** [comment]
:+1: for `npm install --save-dev /path/to/plugin`

**Comment by bucaran** [comment]
@MadcapJake Ready to close?
