### ISSUE TITLE
@taskr/pug compiler

### ISSUE THREAD

**Issue by sadeghbarati** [lukeed/taskr#316]
hey @lukeed only plugin that missing on this task runner is Template Engine compiler

I try to do it with external plugins but relative path and absolute path generate

main pug file and includes with them

**Comment by sadeghbarati** [comment]
that speed of compiling other extensions like sass and es6 buble is super fast
only plugin missing is `pug`

**Comment by lukeed** [comment]
Hey, you should be able to do something like this:

```js
const pug = require('pug');

exports.pug = function * (task) {
	yield task.source('src/*.pug')
		.run({
			every: true,
			*func(file) {
				const html = pug.render(file.data.toString(), {
					/// pug options
				});

				file.data = Buffer.from(html);
				file.base = file.base.replace(/\.pug$/i, '.html');
			}
		})
		.target('dist')
}
```

It's an "inline plugin" – i haven't tested it though

**Comment by lukeed** [comment]
Also, this looks like it may still be compatible: https://github.com/frantic1048/fly-pug

I haven't tested that either (I don't use Pug) – but the majority of old Fly plugins (previous name) still work in this release. I'm _slowly_ improving & extracting a new Taskr & Taskr ecosystem. It's happening on an as-needed basis atm.

Hope that helps!

**Comment by sadeghbarati** [comment]
I think wrote similar code
if I use include or extend in file like

index.pug:
```pug
  body
    include header
    h1 sample pug file
```
generated file must be index.html but result is
`index.html` and `header.html`

I'll check you code and say result here
thanks

**Comment by sadeghbarati** [comment]
I test your codes threw this error in the console:
 `it default failed because the "filename" option is required to use includes and extends with "relative" paths
    at undefined line 9`

at line 9:
`include ./includes/header.pug`

**Comment by sadeghbarati** [comment]
works with `fly-pug` plugin:

``` javascript
'use strict';

const { join } = require('path')
const pug = require('pug');



module.exports = function (task, utils) {
    
    task.plugin('pug', {every: true}, function * (file, opts) {
        // console.log(join(file.dir, file.base));
        
        // if (!opts.filename) {
        //     opts.filename = join(file.dir, file.base)
        // }

        const html = pug.render(file.data.toString(), {
            filename: join(file.dir, file.base),
            pretty: true
        });

        file.data = Buffer.from(html);
        file.base = file.base.replace(/\.pug$/i, '.html');
    });
};
```

**Comment by lukeed** [comment]
Cool, glad you got it working 👍 
It's practically the same thing I posted in my code snippet – except that `filename` is a require option for pug. That should have been the only reason why my snippet failed in its posted form.
