### ISSUE TITLE
Support tasks running in parallel

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#34]
Say you have 10 functions that implement an asynchronous transformation on a data source, each taking about 1 minute to complete. Assume these functions are _truly async_ by relying on native extensions or Node's IO API.

Assign each transform to a different task. If you run all tasks sequentially you will have to wait _at least_ 10 minutes. If you run all tasks in parallel you will have to wait _at least_ 1 minute.

Support _this_.

**Comment by derhuerst** [comment]
[ochestrator](https://www.npmjs.com/package/orchestrator) has been made for this and is used by [gulp](http://gulpjs.com/)

**Comment by ghost** [comment]
@derhuerst That's a valid suggestion, thanks.

Do you have any idea of how easy would it be incorporate _ochestrator_ into a co-routine-based model (like Fly)?

Landing in @0.3.0, basically, `yield` each task in its own `co` call.

``` js
co(function* () {
  yield task
})
```

Like 5 new LOC in total :smile:

**Comment by derhuerst** [comment]
@bucaran No, sry. I haven't had a deep look a fly yet. I don't even know the new ES6 features well enough, since I use gulp with passion.

**Comment by ghost** [comment]
@derhuerst No prob. Thanks for bringing this up though :+1:

**Comment by ghost** [comment]
Landed in [fly@0.3.0](https://github.com/flyjs/fly/releases/tag/0.3.0) :metal:
