### ISSUE TITLE
CLI parses bad arguments

### ISSUE THREAD

**Issue by aweary** [lukeed/taskr#44]
This may be an issue with the `Parsec` package itself, but when using the `fly` CLI it parses arguments in a strange way. Instead of throwing an error when an incorrect flag has been passed it will ignore what it doesn't parse as valid and attempt to run whatever command it may find. It should not be parsing potential flags from incorrect flags; it should require the exact flag needed and nothing more. Some examples:

``` js
fly -vdf
// > fly, 0.3.4
// returns the version, should throw an error that -vdf is not a valid flag

fly -l12312312312
//> Available tasks
//> default
// returns available tasks, should throw an error 

fly -12345
//> [11:02:59] Flying with /Users/xxxx/xxxx/flytest/Flyfile.babel.js...
//> [11:02:59] -12345 not found in Flyfile.
// any argument with a preceeding - should be considered a flag, not a task

```

It should work much like the `node` CLI does, and throw errors if the flags are not valid.

``` js
node -v
// > v0.12.0
// returns node version

node -v123
// > node: bad option: -v123
// throws appropriate error
```

CLI arguments are one thing that should require strict equality between whats defined and whats passed at runtime.

**Comment by ghost** [comment]
Parsec will simply fill in the returned arguments object with whatever data it could gather from your arguments. This was a design decision, but it's not set in stone so I am open to suggestions.

In this case you have clearly stated what the expected behavior should be:

> It should work much like the node CLI does, and throw errors if the flags are not valid.

Basically Parsec needs an option to make it throw an exception when unexpected flags are passed, we can catch that in Fly and act accordingly.

Does that make sense to you?

**Comment by aweary** [comment]
I think it'd be a good idea to include a 'strict mode' of sorts in `parsec` where exact flags are required and then implement that in Fly. We can prevent a lot of potentially strange behavior by being more restrictive with how flags are parsed.

**Comment by ghost** [comment]
Sounds good, would you mind [opening the issue](https://github.com/bucaran/parsec/issues/new) over there?

**Comment by iamstarkov** [comment]
btw, why we are using parsec and not other tools like minimist?

**Comment by iamstarkov** [comment]
as far as this issue is not releveant to fly it should be closed, imo

**Comment by ghost** [comment]
A patch for this lands tonight in Parsec, I will follow up with an update to Fly's dependencies soon.

**Comment by ghost** [comment]
> btw, why we are using parsec and not other tools like minimist?

There is no special reason. I was using `minimist` at first, but I wanted to support an elegant syntax like the one we are currently using. Parsec is also written in ES6 and uses generators, it's also less code and has no deps and it's fully tested.

Let's give Parsec a chance, if things start to break apart suddenly, we'll switch to `minimist`.
