### ISSUE TITLE
Conflict with flightplan package

### ISSUE THREAD

**Issue by Termina1** [lukeed/taskr#45]
There is a https://github.com/pstadler/flightplan package. And it's CLI is also uses fly as a bin name.

**Comment by ghost** [comment]
Hey @Termina1, thanks for bringing this up.

Could you help me compile a list of possible resolution ideas?

**Comment by Termina1** [comment]
I think unless you want to change fly's CLI or convince @pstadler to change flightplan's CLI, you should just add information to readme and a workaround.

But a workaround doesn't come to mind, may be something with npm scripts could do the trick?

**Comment by ghost** [comment]
I understand. This should definitely go into the Wiki, under caveats or similar. I will be adding this later.

I would like to point out that `fly`'s original theme is that of the insect, but that does not change the fact that both CLI use the same name. I wonder what other tools out there are also named `fly`.

**Comment by ghost** [comment]
Addressed in the Wiki, under caveats. Thanks

**Comment by mik01aj** [comment]
Most importantly, this means that you can't have both installed globally.

**Comment by ghost** [comment]
Hey @mik01aj 

> this means that you can't have both installed globally.

Correct. I have `node_modules/.bin` on my `$PATH` so `fly` only works from inside the directory in which I have run `npm i fly`. However, I am sure some people would prefer to have their utilities globally installed.

#### Workarounds
- Symlink `bin/index.js` to a another name `fyl`, `fl`, `fy`, etc.
- Add a script to `package.json` that symlinks this out of the box so you can do `npm run symlink2`.
- Either Flightplan or Fly could make a concession and change the CLI name. I was able to obtain the `fly` package in the npm registry so having you first `npm i fly` and then run Fly with a name _other than_ `fly` would be amusing at best though :stuck_out_tongue_winking_eye: 

#### After Thoughts

On a different note though. I wonder how challenging it would be to write a Flightplan for Fly or viceversa and starting a collaboration effort between both projects. :fireworks:
