### ISSUE TITLE
quickstart lost

### ISSUE THREAD

**Issue by iamstarkov** [lukeed/taskr#46]
I was reading API docs and didnt found "quickstart" linked in the bottom

https://github.com/flyjs/fly/blob/master/docs/README.md#api
https://github.com/flyjs/fly/blob/master/docs/quickstart

**Comment by ghost** [comment]
@iamstarkov Thanks! Here is the [correct link](https://github.com/flyjs/fly/wiki/Quickstart). I can patch this later, but if you send me a PR fixing this I'll merge ASAP.

:+1:

**Comment by iamstarkov** [comment]
something strange, it seems to be okay in the markdown source, but still wrong in rendered version
![screen shot 2015-07-18 at 00 41 08](https://cloud.githubusercontent.com/assets/559321/8758562/c427e4d6-2ce5-11e5-80a7-71bcf6665027.png)
![screen shot 2015-07-18 at 00 42 31](https://cloud.githubusercontent.com/assets/559321/8758583/02aa7732-2ce6-11e5-995c-df015a356646.png)

dunno how to fix this heisenbug =(

**Comment by iamstarkov** [comment]
you can contact github support for this strange behaviour

anyway thx for correct quickstart link

**Comment by ghost** [comment]
Fixed.
