### ISSUE TITLE
fly-plugin keyword

### ISSUE THREAD

**Issue by watilde** [lukeed/taskr#48]
This is good catch: https://github.com/flyjs/fly/pull/47

How about to add the following sentence to the guideline for creating fly-plugin? This make things possible to search awesome plugins easily.

> Set `fly-plugin` to the keyword field in your package.json.

**Comment by ghost** [comment]
Sure, but what about adding the label in the generator too?

**Comment by ghost** [comment]
Added to `generator-fly`.

**Comment by iamstarkov** [comment]
"label" you mean badge or keyword?

**Comment by ghost** [comment]
He is saying to recommend users to add this label to their plugins, but I already went ahead and added it into the generator. Plugin authors are strongly advised to use generator-fly to keep everything consistent across plugins READMEs, npm scripts, etc.

**Comment by iamstarkov** [comment]
get it, thx

**Comment by ghost** [comment]
@watilde Can we close this?

**Comment by watilde** [comment]
@bucaran Thanks! Seems nice. Also, we might need to update this description:

> Search the registry for new plugins by "fly" keyword.
> https://github.com/flyjs/fly/tree/master/docs#plugins

**Comment by ghost** [comment]
Done.

**Comment by iamstarkov** [comment]
so, to be clear. which keyword should plugins use? fly or fly-plugin?

**Comment by ghost** [comment]
`fly-plugin` and `fly`. I think using both is acceptable.

**Comment by iamstarkov** [comment]
should all existing plugins be updated?

**Comment by ghost** [comment]
Unfortunately yes.

**Comment by iamstarkov** [comment]
=(

**Comment by watilde** [comment]
@iamstarkov You've made an improvement a while ago, but I'm sorry to create a small change..

Well, we might can do closing this as resolved. Thanks all.

**Comment by iamstarkov** [comment]
@watilde it’s okay.

**Comment by iamstarkov** [comment]
considering not closing this issue until all the plugins will be updated

**Comment by ghost** [comment]
@iamstarkov and @watilde Thanks for the hard work with all those PR man. :+1:

**Comment by ghost** [comment]
:smile:

**Comment by watilde** [comment]
Thanks all!
