### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by iamstarkov** [lukeed/taskr#50]
why does fly cli use [shell runner](https://github.com/flyjs/fly/blob/master/bin/index.js#L1)?

[gulp use different approach](https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L1)

isnt it bad experience for windows users?

**Comment by iamstarkov** [comment]
cannot test it right now, waiting for modern.ie to be installed
![screen shot 2015-07-22 at 15 14 31](https://cloud.githubusercontent.com/assets/559321/8826125/62ff104c-3084-11e5-9566-2146786d2d6e.png)

**Comment by iamstarkov** [comment]
can verify, that it is kinda working now. "kinda" because it still has errors, but it is another issue

**Comment by iamstarkov** [comment]
in master
![screen shot 2015-07-22 at 16 41 32](https://cloud.githubusercontent.com/assets/559321/8828080/8d6805f8-3090-11e5-8be4-1b6bd106b9e6.png)

linked branch
![screen shot 2015-07-22 at 16 42 08](https://cloud.githubusercontent.com/assets/559321/8828090/a1b72b88-3090-11e5-8a34-3ce91da5ceeb.png)

**Comment by iamstarkov** [comment]
reported about node versions in #56 issue

**Comment by watilde** [comment]
@iamstarkov Hi, could you please try this? https://github.com/flyjs/fly/pull/52#discussion_r35218914

**Comment by iamstarkov** [comment]
yes, it is working now
![screen shot 2015-07-22 at 16 48 40](https://cloud.githubusercontent.com/assets/559321/8828274/9de72458-3091-11e5-8342-3e3edcd7b1b8.png)

**Comment by ghost** [comment]
The shell runner is going away when 0.4.0 land as we will be supporting more node versions from now.

Let's check if things still work after 0.4.0.

**Comment by iamstarkov** [comment]
prefer not to close unfixed issues, it makes them hard to find

**Comment by ghost** [comment]
@iamstarkov Right. By the way, are you running Windows? Does

```
#!/usr/bin/env node --harmony
```

worked for you? I know it works on OSX, but this will fail in some Linuxes.

**Comment by iamstarkov** [comment]
it works on windows.
![screen shot 2015-07-28 at 17 26 16](https://cloud.githubusercontent.com/assets/559321/8935579/cb8f9ec4-354d-11e5-994d-efa124055b90.png)

**Comment by ghost** [comment]
If you run `node --harmony` it will work for sure, but I mean if you pass the `--harmony` flag to the shebang like `bin/index.js` does. 

``` sh
#!/usr/bin/env node --harmony
...
...
```

**Comment by iamstarkov** [comment]
@bucaran can you re-open this issue while it’s not fixed?

**Comment by iamstarkov** [comment]
seems to be working with 0.4.x
![screen shot 2015-08-04 at 19 50 19](https://cloud.githubusercontent.com/assets/559321/9068179/27ca28a0-3ae2-11e5-9a0a-3fb0590f0d84.png)
