### ISSUE TITLE
question: clor instead of chalk

### ISSUE THREAD

**Issue by iamstarkov** [lukeed/taskr#54]
chalk has a great community and mature enough. what is wrong with it?

**Comment by hzlmn** [comment]
They do exactly the same, but clor is Jorge's package so we can be sure, that future changes in package API will not create conflicts for exist code.

**Comment by iamstarkov** [comment]
but why do you not trust chalk used by 4500 modules?

**Comment by MadcapJake** [comment]
Because it's only for coloring text in the console. `clor` is clean, readable and concise. There is really no need to change just because chalk is really popular.

**Comment by iamstarkov** [comment]
okay

**Comment by ghost** [comment]
@iamstarkov Good question and there is an answer for that.

I wrote `clor` way before Fly. At the time I thought `chalk` was just too complicated, so clor is just 30 loc and only one dep.

Now, `clor` does almost everything `chalk` does ([see the README](https://github.com/bucaran/clor)). The usage is more flexible than `chalk` though, supporting _chainable composition_ (a unique feature) as well as `chalk`'s style and as a side effect of overriding `.toString()` to the styled string, it lets me write ES6 like this:

``` js
// fmt.js
import clor from "clor"

export default Object.assign(clor, {
  error: clor.bold.red("%s"),
  path: clor.underline.cyan("%s"),
   ...
})

// reporter.js
import fmt from "./fmt"
import { log } from "fly-util"

export default function () {
  this.on("fly_run", ({ path }) =>
    log(`Flying with ${fmt.path}...`, path))

  .on("flyfile_not_found", ({ error }) =>
    log(`No Flyfile Error: ${fmt.error}`, error))
...
```

**Comment by iamstarkov** [comment]
thanks
