### ISSUE TITLE
how does fly.babel.js

### ISSUE THREAD

**Issue by iamstarkov** [lukeed/taskr#55]
dove into fly source code and cannot get who fly can use babel for Flyfile.babel.js. can you help me?

**Comment by MadcapJake** [comment]
That function is [here](https://github.com/flyjs/fly-util/blob/master/src/findPath.js#L23-L43)

**Comment by iamstarkov** [comment]
okay, got it.

fine, fly is already using interpret. have you seen liftoff, which is usually used coupled with interpret?

**Comment by ghost** [comment]
@MadcapJake Thanks.

@iamstarkov I am completely open to improve `fly-util` :+1:

Now, I remember I checked out liftoff while I was researching other build systems and this came up while reading gulp's source, but honestly I couldn't readily figure out how to use it and felt frustrated :laughing: 

Going over liftoff documentation it appears more complicated than Fly itself. This is still totally open to debate, if you can show me how using liftoff can be implemented or explain how it would help make things better I will absolutely consider it.

**Comment by ghost** [comment]
If anyone has suggestions regarding `fly-util`, I'll see you at the [other end of the rainbow](https://github.com/flyjs/fly-util/issues).
