### ISSUE TITLE
Possibly rename Fly.proto.filter to `reduce`, `transform` or `change`

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#57]
I am not completely against this. I find `filter` an acceptable name, but I agree transform is also a great one. I also like `reduce`.

See #1 for more information.

**Comment by yang-wei** [comment]
`reduce` sounds cool but I think `filter` is the most suitable name.

**Comment by iamstarkov** [comment]
`filter` creates unrelated associations with `filter` methods

**Comment by MadcapJake** [comment]
My vote is still for `filter` but if it had to change I think `modify` is a suitable alternative. `reduce` has the same functional paradigminess that `filter` has; `change` is alright but to me, it evokes mutation of source  more than `modify` does; `transform` isn't six letters, since there are several six-letter alternatives available, why add three letters?

**Comment by ghost** [comment]
> filter creates unrelated associations with filter methods

@iamstarkov Do you mean `Array.prototype.filter`? If not, which `filter` methods?

**Comment by iamstarkov** [comment]
yes, for example. or [ramda.filter](http://ramdajs.com/0.17/docs/#filter)

**Comment by ghost** [comment]
@iamstarkov Well, no problem with keeping this issue open for future discussion. 

Right now I think the focus should be in fixing bugs and start working on essential plugins like `fly-browsersync` or `fly-sync` (should be built in IMO).

**Comment by ghost** [comment]
I doubt this is going to happen, so I'll close this. Anyone really pushing for this change is free to reopen and continue the discussion.

**Comment by iamstarkov** [comment]
why its become not going to happen in ten days?

**Comment by ghost** [comment]
10 days since your comment, but 28 days since the issue was created, which effectively a month. I just published v0.7.0 and plan to release `1.0` very early next month if not before. I think the argument will have to be more convincing to adopt the change.

Let me say this again, I don't really find changing `filter` to another name displeasing, but just making it `transform` does not seem so important.

**Comment by iamstarkov** [comment]
okay
