### ISSUE TITLE
Plugins could support sourcemaps

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#60]
This can be passed via options directly from the Flyfile, but maybe plugins could hide this bit and provide direct support to produce sourcemaps by default or via only one option.

Thoughts?

@watilde @kashiro @morishitter
@MadcapJake @iamstarkov 
@drKraken  @TrySound

**Comment by MadcapJake** [comment]
Earl Grey's generator returns an object with a `code` field and (if flagged) a `map` field.  So extracting would be a simple check if that field exists.  My question is, how would fly handle separate map files?  They shouldn't be sent through the rest of the filters or `concat`, but they should be sent to the same location as src (maybe via `target`?)

**Comment by TrySound** [comment]
@bucaran I think this option should be in .source out of the box. There is a discussion to add this feature to gulp. We can make it faster.

**Comment by ghost** [comment]
I understand that sourcemaps are usually a feature that the transpilers, etc., provide via their own options. Can anyone confirm this?

How each transpiler handles this may be slightly different, and since sourcemaps is a very common feature I thought it would be convenient to have Fly-Plugins deal with this is a transparent manner via `Fly.proto.source()` out of the box.

**Comment by MadcapJake** [comment]
That'd be really cool but there would need to be some way for filters to send the map file somewhere (`this._maps`?) as it can't be returned in `src`.

Then maybe `target` when placing files, would search `_maps` for any associated map file and place it there with the file.

**Comment by ghost** [comment]
We should start with how the Flyfile should look.

At the plugin level:

``` js
this.filter("myPlugin", (source, options) => {

  // if this transformer has special requirements for sourcemaps, we 
  // hide that complexity at the plugin level (the only actor who is 
  // concerned with this issue) and make sure this is always handled
  // in the same way and with the same interface, maybe something like
  translate(options, "sourceMap", ...)
  // else if the sourcemap option is simply `sourceMap` we pass it along...

  return this.defer(myFilter)(source, options)
}, { ext: ".fly" })
```

**Comment by MadcapJake** [comment]
I don't follow your design.  Is `translate` the function that the plugin uses to translate source? Then why is `myFilter` down below in the `defer` function call?

---

Here's what I was thinking plugins would do:

``` js
module.exports = function () {
  const deferredPlugin = (src, opts, cb) => {
    // run your transformer
    this.addSourceMap(sourceMap) // adds to `this._sourceMaps`
    cb(null, compiledSrc.toString()
  }
  this.filter("pluginName", (source, options) => {
    this.defer(deferredPlugin.bind(this))(source, options)
  }, { ext: ".ext", sourceMaps: true }) // plugin author can set default behavior
}
```

That way, sourcemap creation is left to the plugin developer.  `addSourceMap` could also have a conditional inside it: `if (config.sourceMaps) this._sourceMaps.push(sourceMap)`.  Which allows the user to set sourcemaps at the flyfile level.  You could even have the flag cascade down: `set in user's config directory? > set in users project directory? > set in flyfile? > set in task? > set in filter options?` or something along those lines.  This allows the user to decide on sourcemaps for all their flyfiles, specific projects, specific tasks, or specific filters.

Then, I'd say have the `target` function just do a search for `targetName + ".map" + extension` in `_sourceMaps` and place the two files together.

And here's how the cascading option could look:

``` js
export function* task1 () { // sourceMaps is true here due to default below
  return { secret: 42 }
}

export function* task2 ({ secret }, { sourceMaps: false }) {  // overrides default below
  return { secret }
}

export function* task3 ({ secret }) { // sourceMaps is true here due to default below
  this.log(`The secret is ${secret}`)
}

export default function* ({ sourceMaps: true }) { // sets sourceMaps opt for all tasks
  yield this.start(["task1", "task2", "task3"])
}
```

Using an object would also allow you to set additional cascading options later (or even allowing custom user-generated cascading options).  Of course, custom `filter` methods could have the option in the same option object as `ext` and plugin authors could set the default this way as well.

Lastly, you could allow users to have a `.flyrc` file (in home or project dir) or just allow command line option: `--sourcemaps`.

**Comment by ghost** [comment]
Currently working on this.
