### ISSUE TITLE
support reading streams so that the likes of fly-browserify can perform more efficiently

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#67]
@MadcapJake

**Comment by MadcapJake** [comment]
Is this coming in v0.7.0? Are you still planning on using CSP channels?

**Comment by ghost** [comment]
@MadcapJake I want to do something with CSP, but the priority in this issue is to provide at least a stream _adapter_. 

I'd like to land source maps first, and finish a few plugins:
- fly-ember
- fly-emblem
- fly-handlebars

**Comment by MadcapJake** [comment]
those will all be really nice! :+1:

**Comment by danny-andrews** [comment]
After reading through the [docs](https://github.com/bucaran/fly/blob/master/docs/README.md#features) I got the impression that fly worked with streams already. "Fly API allows you to compose tasks similar to a pipeline, but it's not limited to the stream metaphor."

**Comment by ghost** [comment]
@danny-andrews Hmm, you are right, giving it a second thought, that does sound misleading. What I intended to say was that it does not like streams.

**Comment by lukeed** [comment]
Ah, perhaps yes. I first read it & assumed that it meant tasks "piping" (or chaining) into tasks, which Fly _does_ do; but I can see how one could pickup / expect a more literal definition of "stream" from that.

**Comment by lukeed** [comment]
A Stream-like behavior is introduced in `2.0` release. The files array (`fly._.files`) is a series of objects containing `dir`, `base`, and `data` keys. The `data` key is a `Buffer` string that may be manipulated throughout the task's lifecycle, while the remaining two keys are taken from the file's `pathObject` (via `path.format()`).

In addition, you may now attach additional keys + values to each `file` object, and these will persist until the task's final `yield` --- which is usually `target()`.
