### ISSUE TITLE
Add test coverage tools

### ISSUE THREAD

**Issue by yang-wei** [lukeed/taskr#71]
Interested to add test coverage tool like [istanbul](https://github.com/gotwarlost/istanbul) ? We can also use service like [coveralls](https://coveralls.io/) after that.

fly coverage report :laughing: :laughing: :laughing: 

![image](https://cloud.githubusercontent.com/assets/5494874/9153492/fd14625e-3e94-11e5-8f1f-cf9e8431f062.png)

**Comment by yang-wei** [comment]
I think you had intention to add this 

https://github.com/flyjs/fly/blob/master/.gitignore#L14

**Comment by ghost** [comment]
Definitely. Let's keep this open and I will get back to it after the next minor release soon. :smile:

**Comment by yang-wei** [comment]
:+1:

**Comment by iamstarkov** [comment]
istanbul is bad at es6-code, considering isparta instead

**Comment by ghost** [comment]
@iamstarkov Awesome. More homework for me.

**Comment by iamstarkov** [comment]
sorry. find-n-repalce "istanbul→isparta" is good enough

**Comment by ghost** [comment]
Happening in 0.7.0.

**Comment by ghost** [comment]
Ended up happening 0.8.0, sorry for the delay.

Now, I need to up that coverage.

:airplane:  080e84bf348a3b3d485dd78e28e615062748d5ae
