### ISSUE TITLE
Remove examples from main repo and move to another repo

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#74]
Comments?

**Comment by iamstarkov** [comment]
reasons?

**Comment by ghost** [comment]
The examples database is growing, but I still would like to add more complex examples, as well as examples that compile long files to do benchmarks, etc.

Now, if I add an exceptionally large stylesheet to try benchmark fly-less vs fly-sass (just an example), GitHub will end up interpreting Fly as a CSS project :smile: (actually this happened once in the history of the project).

**Comment by ghost** [comment]
You are right :smile: 

Examples are definitely _staying_. It would suck to download Fly and try to access the examples and then find out that you need to follow another step for this.

**Comment by MadcapJake** [comment]
Maybe add a separate repo for larger examples.

**Comment by ghost** [comment]
> Maybe add a separate repo for larger examples.

This. May not even happen, but definitely that would be the way to go.
