### ISSUE TITLE
Assigns `name` to a function

### ISSUE THREAD

**Issue by andy-hanson** [lukeed/taskr#79]
flyjs won't work with bleeding-edge iojs.

In fmt.js, `clor` is a function, and on line 10, `name` is one of the properties assigned to it.

It's possible to assign `name` in newer versions of iojs but it takes some work and probably isn't a good idea. See [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name).

The precise error message is:

```
TypeError: Cannot assign to read only property 'name' of function $(str) {
    return (str === undefined) ?
      $.toString() : clor(s + str + ansi.reset.close)
  }
```

The error is only reproducible by installing the next+1 branch from iojs' [repo](https://github.com/nodejs/node/tree/next+1).

**Comment by ghost** [comment]
Not a problem. Will fix along with the next release.

Thanks! :smile:
