### ISSUE TITLE
separate Fly and CLIEngine

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#80]
_Fly_ the utility people can download via `npm i fly` would continue to be this repo.

The top priority is to move `fly.js` which exports the Fly class should into its module `fly-core`.

`cli/*.js` could stay or go into its own `fly-cli` too. 

The least priority is moving `fmt.js` to `fly-fmt`.

**Comment by MadcapJake** [comment]
Just curious, what makes you want to modularize this project so much?

**Comment by ghost** [comment]
Nothing special. Fly was designed to be its own module originally, but I wanted to keep everything in the same project to make testing easy (didn't even want to use `npm link`). 

Now, that is more or less stable, it felt natural to at least put the `fly-core` in its own module. 

Why? Because anyone could write their own CLIEngine using the hypothetical `fly-core`. Probably not going to happen anyway :smile:
