### ISSUE TITLE
add shell completions

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#81]
I can easily add completions for [fish](https://github.com/fish-shell), but `bash` and company will require some research :)

**Comment by MadcapJake** [comment]
I can help with an oh-my-zsh plugin but that'll just need to be added to their plugin [folder](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins).  I don't know how to auto-install that (or if that's even possible).

**Comment by martoranod** [comment]
What's the status of this?

**Comment by tjbenton** [comment]
https://www.npmjs.com/package/commander-completion could be an easy way to handle this, but the cli would have to be updated to use commander

**Comment by lukeed** [comment]
@jbucaran Should we even both with this now? There aren't any "commands" -- just flags and a list of tasks to run.

```bash
Examples
  fly -p="/demo"
  fly -m=parallel task1 task2
  fly --mode="serial" task1 task2
```

**Comment by jorgebucaran** [comment]
Let's close this!
