### ISSUE TITLE
Notes about plugin API changes

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#83]
I will be sending PRs once 0.7.0 lands, but basically there are two things to be aware:
- Plugins injecting filters **do not** need `try { } catch() {}` blocks anymore.
  
  > This complexity is handled inside the transformer closure created by `Fly.prototype.filter`.
- Transformer plugins receive a raw data argument. If you are doing string / text manipulation, you must convert this data to a string. `data.toString()`, `${data}`, etc.
- In order to support sourcemaps and open the door to future features, transformer plugins using the `Fly.prototype.filter` method can now return an object instead of a string:

``` js
{ code, map, ext }
// or maybe? 
// { data, map, ext }
```
- Inline filters can still return a string / raw data, this has not changed.

**Comment by manland** [comment]
:+1: especially for the sourcemap purpose.

Maybe can you add `this.filterSync()` to encapsulate the code like : 

``` js
this.filter("ts", (data, options) => {
    return this.defer((data, options, cb) => {
        let d = transpile(data.toString(), options, options.fileName);
        cb(null, d);
    })(data.toString(), options)
}, { ext: ".js" });
```

So we (plugins creator) can do something like : 

``` js
this.filterSync("ts", (data, options, cb) => {
    let d = transpile(data.toString(), options, options.fileName);
    cb(null, d);
}, { ext: ".js" });
```

ps : i am not an expert in finding good names, please find a better name than `filterSync` ;)
ps2 : yes, i try to create a plugin to compile ts sources :smile:

**Comment by ghost** [comment]
@manland Hi and thanks! Well, regarding this issue's topic:

Inside filters just return:

``` js
const result = transpile(data.toString(), options)
{ 
  code: result.code,
  map: result.map
  ext: ".js"
}
```

Regarding your suggestion to simplify the _async to promise_ API, let's stick to `proto.defer` for 0.7.0, but I am totally open to suggestions like these for the next one! :smile:

**Comment by manland** [comment]
Thanks for the tips, looks better in my [code](https://github.com/manland/fly-ts/blob/master/index.js#L33) !

**Comment by ghost** [comment]
TS transformer API looks really cool and thanks for writing a plugin for it! :grinning: 

I'll ping you where 0.7.0 is up and help you update it.
