### ISSUE TITLE
Rename not work

### ISSUE THREAD

**Issue by manland** [lukeed/taskr#84]
Thanks for your awesome jobs with this tool !

However,  rename not work.

I have tested, from [examples directory](https://github.com/flyjs/fly/blob/master/examples/rename/flyfile.js)

``` js
this .source('./src/app.js').rename('index.js').target('dist')
```

But i have `failed due to TypeError: _this.source(...).rename is not a function` with `fly: 0.6.1` version.

**Comment by iamstarkov** [comment]
is it the same with latest fly?

**Comment by ghost** [comment]
I am sorry, there is no `rename` method in the prototype as it was not still clear whether this should go into core or userland. Let's use this issue to document what the desired behavior should be first.

**Comment by manland** [comment]
If someone needs to rename its files, I have done a little workaround : 

``` js
export function* vendors () {
    const to = 'dist';
    const from = 'node_modules';
    const vendors = [
        {from: `${from}/rx/dist/rx.js`, to: `${to}/rx.js`},
        {from: `${from}/lodash/index.js`, to: `${to}/lodash.js`},
        {from: `${from}/moment/moment.js`, to: `${to}/moment.js`}
    ];
    const options = {};
    let promises = vendors.map((vendor) => {
        return this.defer((vendor, options, cb) => { fs.copy(vendor.from, vendor.to, options, cb); })(vendor, options);
    });
    yield promises;
}
```

I have used [node-fs-extra](https://github.com/jprichardson/node-fs-extra#copy) but you can use every lib/helper you prefer to copy files (like ncp...).

And run it with : 

``` js
yield this.start([...'vendors'], { parallel: true });
```

Have a good hack ;)

**Comment by ghost** [comment]
@manland Hacker! :smile: 

We need to add `rename` to core or create a `fly-rename` plugin. Thoughts?

**Comment by sylvainpolletvillard** [comment]
The way I understand it, `rename` is a specific usecase for the `target` method that keeps the original directory as destination but removes the source files. I think the `target` method could be more parameterized to deal with most of the usual IO operations.

**Comment by ghost** [comment]
Sure. But overloading `target` is not a good idea. At one point I tried to merge `concat` and `target`, but it was difficult to determine whether target was a `directory/file` or `directory/directory`.

Similar to `concat`, rename could be a filter-like method in the sequence and leave `target` untouched.

``` js
yield this.source("*.e6.js").rename("*.js").target("dist")
```

This smells like a plugin to me. 

@watilde @iamstarkov What do you think?

**Comment by watilde** [comment]
Hi all, I like this discuss.

Feature:
I felt question about the `ext` when I created a plugin. It was difficult to rename the filename, it seems nice to implement `rename` as core code.

Syntax:
I'd like to rename using the argument like a `String.prototype.replace`.

``` js
yield this.source("*.e6.js").replace(".es6.js", ".js").target("dist")
```

**Comment by ghost** [comment]
@watilde Oh, that's clever. So, it should support RegExp of course. 

So, one would use `rename` or `replace` to change the extension only? What about adding a prefix/suffix to the filename?

Here is another interface. This can _only_ be used to change the `name.ext`:

``` js
yield this
  .source("*.es6.js").
  .rename(({ name, ext }) => { //{root, dir, base, ext, name} → path.parse(file)
    return ext === "es6.js" ? `${name}.js` : ""
  })
  .target("dist")
```

> As a rule, if you return `""` we will not modify the value.

**Comment by iamstarkov** [comment]
considering rename for filenames and replace for file contents

**Comment by ghost** [comment]
> considering rename for filenames, and replace for file contents

:+1:

**Comment by watilde** [comment]
@bucaran That's no the only one to change the extension. I mean that's just like real `String.prototype.replace`:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/replace

> considering rename for filenames, and replace for file contents
> :+1:

**Comment by ghost** [comment]
@watilde I like this. In this case, the string to replace would be only the filename and extension, because we can't modify the root or base path at this stage. Perfect.

**Comment by ghost** [comment]
Closing in favor of #90
