### ISSUE TITLE
Handle filters with variable number of arguments

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#86]
Right now is only possible to pass a data and options object into a filter/plugin.

Support passing `data, options, ...rest` to support a variable number of arguments inside filters/plugins:

``` js
//flyfile.js
yield this.source(...).myPlugin(a, b, c).target(...) 
```

``` js
// myPlugin/index.js
module.exports = function (_) {
  this.filter("myPlugin", (data, a, b, c) => {
  })
}
```

**Comment by manland** [comment]
:+1: 

What about pass filepath in addition of data ?

``` js
//flyfile.js
yield this.source(...).myPlugin(a, b, c).target(...) 
```

``` js
// myPlugin/index.js
module.exports = function (_) {
  this.filter("myPlugin", (file, a, b, c) => {
    const filepath = file.filepath;
   const data = file.data;
  })
}
```

It could permit to plugins' creators to make copy of multiple files :

``` js
//flyfile.js
const files = ['lot/of/files'...];
const to = [{'filepath':'/path/to/put']
yield this.source(...).cp(to).target(...) 
```

``` js
// myPlugin/index.js
module.exports = function (_) {
  this.filter("cp", (file, to) => {
    const filepath = file.filepath;
    const data = file.data;
    return this.defer((cb) => fs.writeFile(to[filepath], data, cb);
  })
}
```

With #84 in target ;)

BTW : it permit to me and my `fly-ts` plugin to enable `sourceMap` feature, because TS-api want a filepath to reference the original pathfile (for browser).

**Comment by ghost** [comment]
This feature is essentially done and just waiting to be pushed, but regarding:

> What about pass filepath in addition of data ?

Yes, why not. Filters should only be concerned with manipulating the data and passing it forward, but having the filepath could help with error reporting #85.

>  it permit to me and my fly-ts plugin to enable sourceMap feature, because TS-api want a filepath to reference the original pathfile (for browser).

I see. In that case yes we should pass the filepath somehow.

**Comment by ghost** [comment]
@manland Can you open a new issue with the feature request?

**Comment by manland** [comment]
@bucaran done #88 !

**Comment by ghost** [comment]
:airplane:  080e84bf348a3b3d485dd78e28e615062748d5ae
