### ISSUE TITLE
Feature request : add filepath in addition of data in filters

### ISSUE THREAD

**Issue by manland** [lukeed/taskr#88]
Please add filepath in addition of data in filters params.  it could permit to me and my `fly-ts` plugin to enable `sourceMap` feature, because TS-api want a filepath to reference the original pathfile (for browser).

Example :

``` js
//flyfile.js
yield this.source(...).myPlugin(...).target(...) 
```

``` js
// myPlugin/index.js
module.exports = function (_) {
  this.filter("myPlugin", (file, options) => {
    const filepath = file.filepath;
    const data = file.data;
  })
}
```

Thanks for your awesome job ;)

**Comment by ghost** [comment]
This will break the API again. Well, here we go again :cry:

**Comment by manland** [comment]
After some hack i have found that the option of filter have already the filename (see code)[https://github.com/flyjs/fly/blob/master/src/fly.js#L163].

I think you can add easily the filepath with it ;)

Btw, i have found an inline sourcemap generation for TS ;) No more need the filepath, so you can close this issue or keep it to add the filepath for other use case... As you want :smile:

**Comment by ghost** [comment]
Right, we are doing that because of sourcemaps. 

Nice catch @manland! :+1: :+1:
