### ISSUE TITLE
Inside plugins, should `this` be bound to a filtered version of the Fly instance?

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#9]
See => https://github.com/flyjs/fly/issues/6

**Comment by ghost** [comment]
This may not happen until 0.2.0 or after, so closing for now.

**Comment by TrySound** [comment]
@bucaran Why close, maybe add milestone?

**Comment by ghost** [comment]
@TrySound Good point. Maybe we need to describe a bit in more detail how this could work.

If we bind plugin's default export to a dumbed down version of Fly what could the consequences and what are the properties / methods we will let in?

**Comment by ghost** [comment]
@TrySound  Let's discuss how we would implement this, pros / cons, etc.

**Comment by ghost** [comment]
@flyjs/developers If you would like to continue discussing this issue, feel free to reopen with a proposal :smile:
