### ISSUE TITLE
add `rename` or `replace` method (based in String.proto.replace) to filter filename and extensions

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#90]
Let's discuss here the implications of this addition. I think it would be powerful addition.

@watilde @iamstarkov @MadcapJake @manland

**Comment by petamoriken** [comment]
IMHO, `rename` is better. `replace` is replacing contents of files like `gulp-replace`.
https://www.npmjs.com/package/gulp-replace

**Comment by iamstarkov** [comment]
👍 im on the same board as @petamoriken

**Comment by lukeed** [comment]
With `2.0`, each file object has a `base` key (as described [here](https://github.com/flyjs/fly/issues/67#issuecomment-252768718)). This makes it super easy for any task or plugin to rename a file (or all files).

``` js
module.exports = function () {
  this.plugin('addPrefix', {}, function * (file, opts) {
    file.base = (opts.prefix || 'prod-').concat(file.base);
  });
};

// flyfile.js
exports.default = function * () {
  yield this.source('dist/world.js')
    .addPrefix({prefix: 'hello-'})
    .target('build');
}; //=> build/hello-world.js
```
