### ISSUE TITLE
how to exit process with error code from a plugin?

### ISSUE THREAD

**Issue by deepsweet** [lukeed/taskr#92]
for example:

``` js
import { CLIEngine } from 'eslint';

export async function eslint() {
    await this.defer((options, done) => {
        const cli = new CLIEngine();

        const report = cli.executeOnFiles([ '.' ]);
        const formatter = cli.getFormatter();

        this.log(formatter(report.results));

        if (report.errorCount > 0) {
            done(`${report.errorCount} error(s)`);
        }

        done();
    })();
}
```

there is no "real" error, only failing log, so my git hook doesn't recognize an error.
even `process.exit(1)` doesn't work o_O are you using some kind of process spawn inside?

**Comment by ghost** [comment]
We are inside `co`. So, the way to handle this would be using a notification that does not exist yet that Fly's core understands.

**Comment by deepsweet** [comment]
so... will it be added in future? :)

**Comment by ghost** [comment]
Yes, I think this totally makes sense and it comes just in time with https://github.com/bucaran/fly-eslint/pull/2.

**Comment by pine** [comment]
:+1:

**Comment by lukeed** [comment]
@bucaran recent thoughts? no update since August.

Shall we continue to emit an error, or change `*exec` to throw & exit?

**Comment by lukeed** [comment]
@deepsweet I know it's been a while, but maybe you're still interested.

What I've began doing is `emit`ting plugin errors thru Fly, which then force the task itself to fail. 

``` javascript
this.emit('plugin_error', {plugin: 'name', error: 'message'});
```

Example usage [here](https://github.com/lukeed/fly-xo/blob/master/index.js#L30).

However, it's worth nothing that if you're in `watch` mode, this won't actually kill the whole instance.

Not sure if this is what you're after, but it _does_ fail the task, so maybe.

**Comment by pine** [comment]
Hi @lukeed. I'm a [fly-ava](https://github.com/pine613/fly-ava) maintener.

Your fly-xo plugin does't do `process.exit(1)`, but I think fly-ava should be died exit code non-zero, because I want to notify to me when a CI died.

What do you think so? Thank you.

**Comment by ghost** [comment]
@pine613 Related? https://github.com/bucaran/fly/pull/153

**Comment by lukeed** [comment]
Yes, related. Let's do something about this

**Comment by lukeed** [comment]
Now the example (above) will exit with a non-zero code. 

Closing :)
