### ISSUE TITLE
concat should add a newline after each file

### ISSUE THREAD

**Issue by ghost** [lukeed/taskr#95]
The current concat implementation does not append a new line after the end of the file, which can cause the following bug.

``` js
// single line comment /*
* multi line comment
*/
```

```
Unexpected token *
```

The correct output should be:

``` js

// single line comment 
/*
* multi line comment
*/
```

**Comment by tjbenton** [comment]
Is this going to be an option that you can specify how you want it to be? 

``` js
export default function *(){
 yield this.source(...)
        .uglify()
        .concat("combined.min.js", {
         newLine: ";\n"
        })
        .target(...)
}
```

Also can you update the `base` to have default of `""` so that you don't have to specify the file name in the `concat` function and you can optionally specify it in the `target` function.

``` js
// I didn't test this but it should work
concat (base = "", { newLine = "\n" } = {}) {
  if(typeof base === "object"){
   newLine = base.newLine || newLine
   base = base.base || ""
  }
  this._.catenator = new Catenator(true, base, newLine)
  this._.write = function* ({ dir, data, map }) {
    yield write({ dir, base, data, map, write: appendFile })
  }
  return this
}
```

So that you can do things like this

``` js
export default function *(){
 let combined = "${dist}/${paths.js}/combined.min.js"
 yield this.clear(combined)
 yield this.source(...)
        .uglify()
        .concat()
        .target(combined)
}
```

``` js
export default function *(){
 yield this.clear(...)
 yield this.source(...)
        .uglify()
        .concat({
         base: "combined.min.js",
         newLine: ";\n"
        })
        .target(...)
}
```

**Comment by ghost** [comment]
> Also can you update the base to have default of "" so that you don't have to specify the file name in the concat function and you can optionally specify it in the target function.

Oh, yeah I totally thought about this before, but in the end decided against because I felt it was just simpler to use `concat` for the _file name_ and `target` for the `directory or directories_. I am not ruling this one out just yet, but if we do this we might as well use an option`{ concat: true }` inside target.

> Is this going to be an option that you can specify how you want it to be?

Of course, we want to specify what the linefeed / base should be :+1:

**Comment by ghost** [comment]
I will release a patch to make this work, but will provide the correct solution in the next minor.
