### ISSUE TITLE
Suggestion: Update `Fly.clear` example in docs

### ISSUE THREAD

**Issue by tjbenton** [lukeed/taskr#96]
Currently the [clear](https://github.com/flyjs/fly/blob/master/docs/README.md#flyprototypeclear-paths) says

``` md
#### `Fly.prototype.clear (paths)`

Clears / Deletes all paths including sub directories.
```

You might consider updating that to be clear that you can clear multiple paths since that's what the [clear](https://github.com/flyjs/fly/blob/master/src/fly.js#L137) function allows

`````` md
#### `Fly.prototype.clear (...paths)`

Clears / Deletes all paths including sub directories.

\```js
export default function* () {
  yield this.clear("dist/main.js", "dist/plugins/**/*.js");
  ...
}
\```

``````

**Comment by ghost** [comment]
LGTM. Want to send me a PR?

**Comment by ghost** [comment]
cd54fcd
